/// <reference types="vite/client" />
/**
 * Responsive WebP versions of photos (generated by scripts/buildImageVariants.mjs into
 * public/img-cache/). Anything not in the index — a fresh upload, or a build without
 * ffmpeg — is served as the original, so this can never break an image.
 */
const modules = import.meta.glob<Record<string, number[]>>('../../public/img-cache/index.json', {
  eager: true,
  import: 'default',
});
const VARIANTS: Record<string, number[]> = Object.values(modules)[0] ?? {};

/** "/uploads/doctors/x.jpg" or "/karusel/y.jpg" from any absolute/relative form of the URL. */
function variantSourceKey(src: string): { lookup: string; cachePath: string } | null {
  const uploads = src.match(/\/uploads\/[^\s?#]+/)?.[0];
  if (uploads) return { lookup: uploads, cachePath: `u/${uploads.slice('/uploads/'.length)}` };
  if (src.startsWith('/') && !src.startsWith('//')) {
    const clean = src.split(/[?#]/)[0];
    return { lookup: clean, cachePath: `s/${clean.slice(1)}` };
  }
  return null;
}

export interface ResponsiveImage {
  src: string;
  srcSet?: string;
}

/**
 * src + srcSet for an <img>. `src` is the variant closest to `fallbackWidth` (used by
 * browsers without srcset support and by crawlers); the browser picks from srcSet by `sizes`.
 */
export function responsiveImage(src: string, fallbackWidth = 960): ResponsiveImage {
  const key = variantSourceKey(src);
  const widths = key ? VARIANTS[key.lookup] : undefined;
  if (!key || !widths?.length) return { src };
  const url = (width: number) => `/img-cache/${key.cachePath}-${width}.webp`;
  const fallback = widths.reduce((best, width) => (Math.abs(width - fallbackWidth) < Math.abs(best - fallbackWidth) ? width : best));
  return {
    src: url(fallback),
    srcSet: widths.length > 1 ? widths.map((width) => `${url(width)} ${width}w`).join(', ') : undefined,
  };
}

export function hasImageVariants(src: string): boolean {
  const key = variantSourceKey(src);
  return Boolean(key && VARIANTS[key.lookup]?.length);
}
