/**
 * Ruscha preyskurant nomlarini inglizchaga professional tarjima qilish.
 */
import exactEn from '../data/priceTranslationsEn.json';
import { normalizePriceRu } from './normalizePriceRu';

const EXACT_PHRASES_EN: [string, string][] = [
  ['Первичный осмотр врача дерматовениролога', 'Primary dermatovenereologist consultation'],
  ['Повторный осмотр врача дерматовениролога', 'Follow-up dermatovenereologist consultation'],
  ['Первичный осмотр врача трихолога + трихоскопия', 'Primary trichologist consultation + trichoscopy'],
  ['Повторный осмотр врача трихолога', 'Follow-up trichologist consultation'],
  ['Первичный осмотр врача дерматоонколога + дерматоскопия', 'Primary dermato-oncologist consultation + dermatoscopy'],
  ['Повторная консультация к врачу дерматоонколога', 'Follow-up dermato-oncologist consultation'],
  [
    'Первичный осмотр врача дерматокосметолога + сканирование лица на аппарате JANUS PRO',
    'Primary dermatocosmetologist consultation + JANUS PRO facial scan',
  ],
  ['Повторный осмотр врача дерматокосметолога', 'Follow-up dermatocosmetologist consultation'],
  ['Первичная консультация подолога', 'Primary podiatrist consultation'],
  ['Повторный осмотр подолога', 'Follow-up podiatrist consultation'],
  [
    'Микрографическое хирургическое удаление злокачественных новообразований кожи по методу "Mohs" (базовый пакет с привлечением пластического хирурга)',
    'Mohs micrographic surgery for malignant skin lesions (basic package with plastic surgeon)',
  ],
  [
    'Микрографическое хирургическое удаление злокачественных новообразований кожи по методу "Mohs" (базовый пакет)',
    'Mohs micrographic surgery for malignant skin lesions (basic package)',
  ],
  [
    'Микрографическое хирургическое удаление злокачественных новообразований кожи по методу "Mohs" в периорбитальной области (реконструктивный этап выполняется офтальмохирургом, д.м.н.)',
    'Mohs micrographic surgery in the periorbital area (reconstructive stage by ophthalmic surgeon, MD, PhD)',
  ],
  [
    'Радиоволновая хирургия 1 образования (доброкачественные внутридермальные новообразования кожи - родинки/невусы) с анестезией',
    'Radiofrequency surgery of 1 lesion (benign intradermal moles/nevi) with anesthesia',
  ],
  [
    'Радиоволновая хирургия 1 образования (доброкачественные эпидермальные новообразования кожи - кератомы, родинки/невусы) с анестезией',
    'Radiofrequency surgery of 1 lesion (benign epidermal keratomas, moles/nevi) with anesthesia',
  ],
  [
    'Радиоволновая хирургия 1 образования в сложных анатомических зонах (веки, паховая область, слизистые) с анестезией',
    'Radiofrequency surgery of 1 lesion in complex anatomical areas (eyelids, groin, mucosa) with anesthesia',
  ],
  [
    'Радиоволновое удаление контагиозного моллюска (за 1 элемент): до 10 образований',
    'Radiofrequency removal of molluscum contagiosum (per lesion): up to 10 lesions',
  ],
  [
    'Хирургическое удаление доброкачественных новообразований кожи больших размеров и новообразований кожи, которые расположены в анатомически сложных участках І уровня сложности',
    'Surgical removal of large benign skin lesions and level I anatomically complex skin lesions',
  ],
  ['Shave (Шейв) - удаление новообразований кожи', 'Shave excision of skin lesions'],
  ['Удаление родинок (от)', 'Mole removal (from)'],
  ['Удаление новообразований (от)', 'Lesion removal (from)'],
  ['Панч-биопсия', 'Punch biopsy'],
  ['Гистологическое исследование', 'Histopathology examination'],
  ['Операция (Базалиома)', 'Surgery (basal cell carcinoma)'],
  [
    'Лазерное удаление доброкачественных новообразований на аппарате DEKA SmartXide Punto CO₂',
    'Laser removal of benign lesions with DEKA SmartXide Punto CO₂',
  ],
  ['Лазерное удаление (за 1 элемент)', 'Laser removal (per lesion)'],
  ['Удаление образований в интимной зоне (до 5 мм)', 'Lesion removal in intimate area (up to 5 mm)'],
  ['Удаление образований в интимной зоне (от 5 мм)', 'Lesion removal in intimate area (from 5 mm)'],
  ['Удаление образований в области верхних и нижних век (от 1 до 3 мм)', 'Lesion removal on upper/lower eyelids (1–3 mm)'],
  ['Удаление образований в области верхних и нижних век (от 5 мм)', 'Lesion removal on upper/lower eyelids (from 5 mm)'],
  ['Первая степень сложности (один-два элемента)', 'Complexity level I (1–2 lesions)'],
  ['Вторая степень сложности (от трех до семи элементов)', 'Complexity level II (3–7 lesions)'],
  ['Третья степень сложности (от восьми до пятнадцати элементов)', 'Complexity level III (8–15 lesions)'],
  [
    'Криохирургия немеланомных злокачественных опухолей кожи (Базальноклеточный карцинома, плоскоклеточная карцинома)',
    'Cryosurgery for non-melanoma skin cancers (basal cell and squamous cell carcinoma)',
  ],
  [
    'Криохирургия предраковых состояний кожи (лейкоплакия, актинический кератоз, актинический хейлит, болезнь Боуэна)',
    'Cryosurgery for precancerous skin conditions (leukoplakia, actinic keratosis, actinic cheilitis, Bowen disease)',
  ],
  ['Криодеструкция рубца аэрозольным методом', 'Aerosol cryodestruction of scar tissue'],
  ['Лазерное удаление вен на нижних конечностях (от)', 'Laser removal of leg veins (from)'],
  [
    'Лазерное лечение гемангиом, ангиом, сосудистых новообразований (от)',
    'Laser treatment of hemangiomas, angiomas and vascular lesions (from)',
  ],
  ['Удаление пигментации всего лица', 'Full-face pigmentation removal'],
  ['Лазерное удаление сосудистых звёздочек на лице (от)', 'Laser removal of facial spider veins (from)'],
  ['Лазерное удаление телеангиэтазий на всём теле (от)', 'Laser treatment of body telangiectasias (from)'],
  ['Лазерное удаление телеангиэтазий на крыльях носа (от)', 'Laser treatment of nasal wing telangiectasias (from)'],
  ['Лечение онихомикоза ногтей (от)', 'Onychomycosis treatment (from)'],
  ['Лазерное лечение гемангиом (от)', 'Laser treatment of hemangiomas (from)'],
  [
    'Лазерное лечение бородавок с помощью аппарата PinPoint laser за 1 кв.см (1 сеанс)',
    'PinPoint laser wart treatment (per 1 cm², 1 session)',
  ],
  ['Инъекция в/м без расходного материала', 'Intramuscular injection without consumables'],
  ['Капельница без расходных материалов', 'IV drip without consumables'],
  ['Женские руки полностью', "Women's full arms"],
  ['Женские ноги полностью', "Women's full legs"],
  ['Лицо полностью', 'Full face'],
  ['Кисти рук и пальцы', 'Hands and fingers'],
  ['Тыл стоп + пальцы', 'Sole and toes'],
  ['Задняя часть шеи', 'Back of neck'],
  ['Межбровье', 'Glabella'],
  ['Антитела к токсоплазме', 'Antibodies to Toxoplasma'],
  ['Антитела к ЦМВ', 'Antibodies to CMV'],
  ['Антитела к ВПГ', 'Antibodies to HSV'],
  ['Антитела к краснухе', 'Antibodies to rubella'],
  ['Лечение пигментации', 'Pigmentation treatment'],
  ['Лазерная эпиляция', 'Laser hair removal'],
  ['Фотоомоложение', 'Photorejuvenation'],
  ['Биоревитализация', 'Biorevitalization'],
  ['Мезотерапия', 'Mesotherapy'],
  ['Плазмотерапия', 'PRP therapy'],
  ['Криохирургия', 'Cryosurgery'],
  ['Фототерапия', 'Phototherapy'],
  ['Криодеструкция доброкачественных глубоких новообразований кожи', 'Cryodestruction of benign deep skin lesions'],
  ['Криодеструкция доброкачественных поверхностных новообразований кожи', 'Cryodestruction of benign superficial skin lesions'],
  ['Криодеструкция рубца контактным методом', 'Contact-method scar cryodestruction'],
  ['Лечение акне, красноты, пост-акне (gold toning)', 'Acne, redness and post-acne treatment (gold toning)'],
  ['Аллергопроба 10 пунктов', 'Allergy test (10 points)'],
  ['Инъекция с метотриксатом', 'Methotrexate injection'],
  ['Инъекция с метотриксатом 0.75', 'Methotrexate injection 0.75'],
  ['Обработка кожи без учета лекарственных препаратов', 'Skin treatment without medication costs'],
  ['Обработка кожи с учетом лекарственных препаратов', 'Skin treatment including medication costs'],
  ['Обработка раны первичная', 'Primary wound treatment'],
  ['Обработка раны повторная', 'Follow-up wound treatment'],
  ['Инъекции для похудения DERMAQUAL SUPREALL', 'DERMAQUAL SUPREALL weight-loss injections'],
  ['Мезотерапия: Инъекции для похудения DERMAQUAL SUPREALL (франция)', 'Mesotherapy: DERMAQUAL SUPREALL weight-loss injections (France)'],
  ['Тело (10х10)', 'Body (10×10 cm)'],
  ['Тело (20х20)', 'Body (20×20 cm)'],
  ['Дерматоскопия тела + база данных', 'Body dermatoscopy + database'],
  ['Трихопигментация (голова) 50%', 'Trichopigmentation (scalp) 50%'],
  ['Трихопигментация (голова)100%', 'Trichopigmentation (scalp) 100%'],
  ['Аппаратная чистка стопы', 'Device-based foot cleansing'],
  ['Обработка мозоли без стерженя', 'Callus treatment without core'],
  ['Обработка мозоли со стерженем', 'Callus treatment with core'],
  ['Удаление вросшего ногтя', 'Ingrown nail removal'],
  ['Аппаратная чистка ногтей', 'Device-based nail cleansing'],
  ['Омоложение кожи лица (без глаз)', 'Facial skin rejuvenation (excluding eye area)'],
  ['Омоложение зоны вокруг глаз', 'Periorbital rejuvenation'],
  ['Омоложение лица и шеи', 'Face and neck rejuvenation'],
  ['Омоложение лица и зоны вокруг глаз', 'Face and periorbital rejuvenation'],
  ['Омоложение кожи лица, шеи и декольте', 'Facial, neck and décolleté rejuvenation'],
  ['Омоложение лица, шеи, зоны декольте, вокруг глаз', 'Face, neck, décolleté and periorbital rejuvenation'],
  ['Омоложение зоны тела до 400 см²', 'Body area rejuvenation up to 400 cm²'],
  ['Омоложение зоны тела 800', 'Body area rejuvenation 800 cm²'],
  ['ВЛОК аппарат (внутривенное лазерное облучение)', 'IVL device (intravenous laser therapy)'],
  ['Me Line пилинг против пигментации', 'Me Line pigmentation peel'],
  ['Инъекция в/в без расходных материалов', 'IV injection without consumables'],
  ['Лечение купероза и розации', 'Couperose and rosacea treatment'],
  ['Лечение онихомикоза ногтей 1 ноготь', 'Onychomycosis treatment (1 nail)'],
  ['Коррекция рубца', 'Scar correction'],
  ['Face art лечение розацеа акне', 'Face Art rosacea and acne treatment'],
  ['Удаление татуажа бровей', 'Eyebrow permanent makeup removal'],
  ['Забор крови', 'Blood draw'],
  ['Лечение пигментации лицо', 'Facial pigmentation treatment'],
  ['Лечение пигментации щеки', 'Cheek pigmentation treatment'],
  ['Осветление зоны бикини', 'Bikini area lightening'],
  ['Удаление татуировки 6 см', 'Tattoo removal 6 cm'],
  ['Лечение рубцов 5 см²', 'Scar treatment 5 cm²'],
  ['ХГЧ', 'hCG'],
  ['Холестерин Общ.', 'Total cholesterol'],
  ['3х-стаканная проба мочи', 'Three-glass urine test'],
  ['ХГ в моче', 'hCG in urine'],
  ['Нативный мазок на трихомониаз', 'Native smear for trichomoniasis'],
  ['Женский мазок на лептотрихоз', "Women's smear for leptotrichosis"],
  ['Проба Шуварского – Симса Гунера', 'Shwartzman–Sims–Gunner test'],
  ['Проба на антиспермальные антитела', 'Antisperm antibody test'],
  [
    'Дыхательно- уреазный тест на определение Helicobacter pylory',
    'Breath urease test for Helicobacter pylori detection',
  ],
  ['Тимоловая проба', 'Thymol test'],
  ['Общий холестерин', 'Total cholesterol'],
  ['HDL-холестерин (Высокой плотности)', 'HDL cholesterol (high density)'],
  ['LDL-холестерин (Низкой плотности)', 'LDL cholesterol (low density)'],
  ['Холинэстераза', 'Cholinesterase'],
  ['Проба Реберга', 'Rehberg test'],
  ['Хлориды (Cl)', 'Chlorides (Cl)'],
  ['Мозговой натрийуретический пептид (NT pro BNP)', 'Brain natriuretic peptide (NT-proBNP)'],
  ['ХГЧ – ранняя диагностика беременности', 'hCG — early pregnancy detection'],
  ['ХГЧ – точное разведение', 'hCG — precise dilution'],
  ['Увлажняющий крем для очень сухой кожи 340мл', 'Moisturizing cream for very dry skin 340 ml'],
  ['Увлажняющий лосьон для очень сухой кожи 236мл', 'Moisturizing lotion for very dry skin 236 ml'],
  ['Очищающий гель против несовершенств 236мл', 'Cleansing gel for blemishes 236 ml'],
  ['Цераве гель против несовершенств с ана и вна кислотами', 'CeraVe blemish gel with AHA and BHA acids'],
  ['Очищающий крем-гель для нормальной и сухой кожи 236мл', 'Cleansing cream-gel for normal and dry skin 236 ml'],
  ['dercos dandruff and scalp для нормальных и жирных 200мл', 'Dercos dandruff and scalp shampoo for normal and oily hair 200 ml'],
  ['Vichi Dercos шампунь пилинг против перхоти 250мл', 'Vichy Dercos anti-dandruff peeling shampoo 250 ml'],
  ['Vichi Dercos против перхоти для чувствительной кожи головы 200мл', 'Vichy Dercos anti-dandruff shampoo for sensitive scalp 200 ml'],
  ['Vichi Dercos против перхоти для жирных волос 200мл', 'Vichy Dercos anti-dandruff shampoo for oily hair 200 ml'],
  ['Vichi Dercos против перхоти для жирных волос 390мл', 'Vichy Dercos anti-dandruff shampoo for oily hair 390 ml'],
  ['Vichi Dercos против перхоти для сухих волос 200мл', 'Vichy Dercos anti-dandruff shampoo for dry hair 200 ml'],
  ['Vichi Dercos против перхоти для сухих волос 390мл', 'Vichy Dercos anti-dandruff shampoo for dry hair 390 ml'],
  ['Vichi Dercos шампунь кондиционер против пехоти 2 в 1 200мл', 'Vichy Dercos 2-in-1 anti-dandruff shampoo conditioner 200 ml'],
  ['Vichi Dercos шампунь кондиционер против пехоти 2 в 1 390мл', 'Vichy Dercos 2-in-1 anti-dandruff shampoo conditioner 390 ml'],
  ['Vichi Dercos регулир шампунь для жирных волос 200мл', 'Vichy Dercos regulating shampoo for oily hair 200 ml'],
  ['Vichi Dercos успокаивающий шампунь для нормальных и жирных волос 200мл', 'Vichy Dercos soothing shampoo for normal and oily hair 200 ml'],
  ['Vichi термальная вода 15мл', 'Vichy thermal water 15 ml'],
  ['Виши минерал 89 увлажняющий крем 72ч для сухой кожи 50мл', 'Vichy Mineral 89 moisturizing cream 72h for dry skin 50 ml'],
  ['ЛРп гиалу B5 сыворотка для вокруг глаз 15мл', 'La Roche-Posay Hyalu B5 eye serum 15 ml'],
  ['ЛРП флюид против пигментации спф +50 50мл', 'La Roche-Posay anti-pigmentation fluid SPF 50+ 50 ml'],
  ['Дерма Хел-PRP', 'Derma Heal PRP'],
  [
    'Vichi Dercos аминексил средство для волос для женщин 21 монодоза 6мл',
    'Vichy Dercos Aminexil hair treatment for women, 21 single doses 6 ml',
  ],
  [
    'Vichi Dercos аминексил средство для волос для мужчин 21 монодоза 6мл',
    'Vichy Dercos Aminexil hair treatment for men, 21 single doses 6 ml',
  ],
  [
    'Vichi Dercos энерджи шампунь против выпадения волос 400мл',
    'Vichy Dercos Energy anti-hair loss shampoo 400 ml',
  ],
  [
    'Vichi Dercos энерджи шампунь против выпадения волос 200мл',
    'Vichy Dercos Energy anti-hair loss shampoo 200 ml',
  ],
  ['Vichi Dercos тонизирующий кондиционер для волос 200мл', 'Vichy Dercos tonifying hair conditioner 200 ml'],
  ['Vichi Dercos псолюшн кераторегулирующий шампунь 200мл', 'Vichy Dercos kerato-regulating Solution shampoo 200 ml'],
  ['Антитела к', 'Antibodies to'],
  ['Свобод. Хорионич. гонадотропин (Free-B-HCG)', 'Free beta-hCG (chorionic gonadotropin)'],
  [
    'Нейрон специфическая енолаза (NSE - лёгкие)',
    'Neuron-specific enolase (NSE — lungs)',
  ],
  [
    'Хорионический гонадотропин (ХГЧ - яички, пуз. занос)',
    'Chorionic gonadotropin (hCG — testicular, ectopic pregnancy)',
  ],
  ['Простатспецифический антиген общий (PSA)', 'Total prostate-specific antigen (PSA)'],
  ['Простатспецифический антиген свобод. (Free-PSА)', 'Free prostate-specific antigen (Free-PSA)'],
  ['Трихомонада Trichomonas vaginalis', 'Trichomonas vaginalis'],
  ['Антитела к митохондриям (АМА)', 'Antimitochondrial antibodies (AMA)'],
  [
    'IgG к одноцепочечнойДНК, IgG к двухцепочечнойДНК',
    'IgG to single-stranded DNA, IgG to double-stranded DNA',
  ],
  ['Антитела к эхинококку IgG', 'Anti-echinococcus IgG antibodies'],
  [
    'Гельминты (токсокароз, описторхоз, трихенеллёз,',
    'Helminths (toxocariasis, opisthorchiasis, trichinellosis,',
  ],
  ['Эхинококкоз)', 'echinococcosis)'],
  [
    'Anti Hbs (Антитела к поверхностному антигену гепатита B)',
    'Anti-HBs (hepatitis B surface antigen antibodies)',
  ],
  ['С 3х точек (urethra.vagina.cervical)', 'From 3 sites (urethra, vagina, cervical)'],
  ['Антитела к вирусу краснухи IgM', 'Anti-rubella virus IgM antibodies'],
  ['Антитела к вирусу краснухи IgG', 'Anti-rubella virus IgG antibodies'],
  ['Антитела к хламидиям IgM', 'Anti-chlamydia IgM antibodies'],
  ['Антитела к хламидиям IgG', 'Anti-chlamydia IgG antibodies'],
  ['Антитела к трихомонаде IgG', 'Anti-trichomonas IgG antibodies'],
  ['Антитела к хламидиям пневм. по IgM IgG', 'Anti-Chlamydia pneumoniae IgM/IgG antibodies'],
  [
    'Неинвазивное определение пола плода. Определние риска развития аномалий хромосомного набора плода. Экспертный тест. (точность 99.9 %)',
    'Non-invasive fetal sex determination. Expert test for fetal chromosomal abnormality risk (99.9% accuracy)',
  ],
  [
    'Иммуногенетика IL 28- B в прогнозе противовирусной терапии при ВГС',
    'IL28B immunogenetics for HCV antiviral therapy prognosis',
  ],
  [
    'TORCH Ig M ИХЛА (токсоплазма, ЦМВ, хламадия, микоплазма, уреоплазма, рубелла., герпес I, ll тип)',
    'TORCH IgM ELISA (toxoplasma, CMV, chlamydia, mycoplasma, ureaplasma, rubella, herpes types I/II)',
  ],
  [
    'TORCH Ig G ИХЛА (токсоплазма, ЦМВ, хламадия, микоплазма, уреоплазма, рубелла., герпес I, ll тип)',
    'TORCH IgG ELISA (toxoplasma, CMV, chlamydia, mycoplasma, ureaplasma, rubella, herpes types I/II)',
  ],
  [
    'СА-50 маркер гастроинестинальных новообразования в первую очередь желудочной железы',
    'CA-50 marker of gastrointestinal lesions, primarily gastric',
  ],
  [
    'HER-2 рецептр один из наиболее значимых молекулярных маркеров при раке молочной зелёз',
    'HER-2 receptor — key molecular marker in breast cancer',
  ],
  [
    'PRO-GRP Прогастрин высвобождающий белок высокочувствительных маркер мелкоклеточного рака лёгких',
    'PRO-GRP (progastrin-releasing peptide) — high-sensitivity small cell lung cancer marker',
  ],
  [
    'Скрин Микоз РТ-ПЦР(выявление и типированиевозбудителей грибковых инфекций)',
    'Mycosis PCR screen (fungal pathogen detection and typing)',
  ],
];

const WORDS_EN: Record<string, string> = {
  первичный: 'primary',
  первичная: 'primary',
  повторный: 'follow-up',
  повторная: 'follow-up',
  осмотр: 'examination',
  консультация: 'consultation',
  врача: 'physician',
  врачу: 'physician',
  врач: 'physician',
  удаление: 'removal',
  лечение: 'treatment',
  операция: 'surgery',
  биопсия: 'biopsy',
  панч: 'punch',
  гистологическое: 'histopathology',
  исследование: 'examination',
  исследования: 'examination',
  новообразований: 'lesions',
  новообразования: 'lesion',
  новообразование: 'lesion',
  образований: 'lesions',
  образования: 'lesion',
  образование: 'lesion',
  кожи: 'skin',
  коже: 'skin',
  кожа: 'skin',
  родинки: 'moles',
  родинка: 'mole',
  невусы: 'nevi',
  невус: 'nevus',
  кератомы: 'keratomas',
  кератома: 'keratoma',
  анестезией: 'with anesthesia',
  анестезия: 'anesthesia',
  лазерное: 'laser',
  лазерная: 'laser',
  лазерный: 'laser',
  лазер: 'laser',
  доброкачественных: 'benign',
  доброкачественные: 'benign',
  злокачественных: 'malignant',
  эпидермальных: 'epidermal',
  эпидермальные: 'epidermal',
  внутридермальные: 'intradermal',
  внутридермальных: 'intradermal',
  хирургическое: 'surgical',
  хирургическая: 'surgical',
  хирургический: 'surgical',
  микрографическое: 'micrographic',
  радиоволновая: 'radiofrequency',
  радиоволновое: 'radiofrequency',
  радиоволновой: 'radiofrequency',
  контагиозного: 'contagiosum',
  моллюска: 'molluscum',
  элемент: 'lesion',
  элементов: 'lesions',
  элементы: 'lesions',
  за: 'per',
  от: 'from',
  до: 'up to',
  с: 'with',
  и: 'and',
  на: 'on',
  в: 'in',
  по: 'by',
  методу: 'method',
  пакет: 'package',
  базовый: 'basic',
  базовая: 'basic',
  привлечением: 'with involvement of',
  пластического: 'plastic',
  хирурга: 'surgeon',
  лицо: 'face',
  лица: 'facial',
  лице: 'face',
  щеки: 'cheeks',
  щека: 'cheek',
  нос: 'nose',
  носа: 'nose',
  лоб: 'forehead',
  шея: 'neck',
  шеи: 'neck',
  декольте: 'décolleté',
  руки: 'arms',
  рук: 'hand',
  ноги: 'legs',
  ног: 'leg',
  волосы: 'hair',
  волос: 'hair',
  ногтей: 'nails',
  ноготь: 'nail',
  ногтя: 'nail',
  зона: 'area',
  зоны: 'area',
  бикини: 'bikini',
  бровей: 'eyebrows',
  татуажа: 'permanent makeup',
  татуировки: 'tattoo',
  татуировка: 'tattoo',
  пигментации: 'pigmentation',
  пигментация: 'pigmentation',
  пигментацию: 'pigmentation',
  рубцов: 'scars',
  рубца: 'scar',
  рубц: 'scar',
  акне: 'acne',
  розацеа: 'rosacea',
  розации: 'rosacea',
  купероза: 'couperose',
  купероз: 'couperose',
  гемангиом: 'hemangiomas',
  гемангиомы: 'hemangiomas',
  ангиом: 'angiomas',
  ангиомы: 'angiomas',
  сосудистых: 'vascular',
  сосудистые: 'vascular',
  звездочек: 'spider veins',
  звёздочек: 'spider veins',
  телеангиэтазий: 'telangiectasias',
  телеангиэтазии: 'telangiectasias',
  вен: 'veins',
  вены: 'vein',
  нижних: 'lower',
  конечностях: 'limbs',
  конечностей: 'limbs',
  крыльях: 'wings',
  всём: 'whole',
  теле: 'body',
  телу: 'body',
  чистка: 'cleansing',
  механическая: 'manual',
  ультразвуковая: 'ultrasonic',
  уход: 'care',
  фотоомоложение: 'photorejuvenation',
  фототерапия: 'phototherapy',
  эпиляция: 'hair removal',
  эпиляции: 'hair removal',
  криодеструкция: 'cryodestruction',
  криохирургия: 'cryosurgery',
  биоревитализация: 'biorevitalization',
  мезотерапия: 'mesotherapy',
  плазмотерапия: 'PRP therapy',
  контурная: 'contour',
  пластика: 'plasty',
  губ: 'lips',
  инъекции: 'injections',
  инъекция: 'injection',
  инъекционная: 'injection',
  ботулотоксина: 'botulinum toxin',
  ботулотоксин: 'botulinum toxin',
  процедура: 'procedure',
  процедуры: 'procedure',
  процедур: 'procedures',
  сеанс: 'session',
  сеанса: 'session',
  серия: 'session',
  серии: 'session',
  осветление: 'lightening',
  коррекция: 'correction',
  шлифовка: 'resurfacing',
  абляционная: 'ablative',
  абляционной: 'ablative',
  глубокая: 'deep',
  средняя: 'medium',
  поверхностная: 'superficial',
  пилинг: 'peel',
  карбоновый: 'carbon',
  пост: 'post',
  качественный: 'qualitative',
  количественный: 'quantitative',
  антитела: 'antibodies',
  антител: 'antibodies',
  кровь: 'blood',
  крови: 'blood',
  слюна: 'saliva',
  слюны: 'saliva',
  гепатит: 'hepatitis',
  туберкулез: 'tuberculosis',
  анализ: 'test',
  тест: 'test',
  забор: 'collection',
  бесплатно: 'free',
  интимной: 'intimate',
  интимная: 'intimate',
  области: 'area',
  область: 'area',
  век: 'eyelids',
  веки: 'eyelids',
  верхних: 'upper',
  верхняя: 'upper',
  верхние: 'upper',
  нижние: 'lower',
  мм: 'mm',
  см: 'cm',
  первая: 'first',
  вторая: 'second',
  третья: 'third',
  степень: 'level',
  сложности: 'complexity',
  сложность: 'complexity',
  одного: 'one',
  один: 'one',
  два: 'two',
  двух: 'two',
  трех: 'three',
  трёх: 'three',
  семи: 'seven',
  восьми: 'eight',
  пятнадцати: 'fifteen',
  аэрозольным: 'aerosol',
  методом: 'method',
  немеланомных: 'non-melanoma',
  опухолей: 'tumors',
  опухоли: 'tumor',
  базальноклеточный: 'basal cell',
  плоскоклеточная: 'squamous cell',
  карцинома: 'carcinoma',
  предраковых: 'precancerous',
  состояний: 'conditions',
  состояния: 'condition',
  лейкоплакия: 'leukoplakia',
  актинический: 'actinic',
  актиническая: 'actinic',
  кератоз: 'keratosis',
  хейлит: 'cheilitis',
  болезнь: 'disease',
  боуэна: 'Bowen',
  женские: "women's",
  женская: "women's",
  женский: "women's",
  женское: "women's",
  мужские: "men's",
  мужская: "men's",
  мужской: "men's",
  полностью: 'full',
  кисти: 'hands',
  пальцы: 'fingers',
  пальцев: 'fingers',
  тыл: 'sole',
  стоп: 'foot',
  стопы: 'feet',
  задняя: 'back',
  часть: 'part',
  части: 'part',
  губа: 'lip',
  губы: 'lips',
  включая: 'including',
  ареолы: 'areolae',
  молочных: 'mammary',
  желез: 'glands',
  белая: 'white',
  линия: 'line',
  живота: 'abdomen',
  живот: 'abdomen',
  спина: 'back',
  спины: 'back',
  бедер: 'thigh',
  колена: 'knee',
  локтя: 'elbow',
  локоть: 'elbow',
  ягодицы: 'buttocks',
  классическое: 'classic',
  подмышечные: 'axillary',
  впадины: 'folds',
  бакенбарды: 'sideburns',
  бородавок: 'warts',
  помощью: 'using',
  аппарата: 'device',
  кв: 'sq',
  рубец: 'scar',
  стрии: 'stretch marks',
  тело: 'body',
  генотипирование: 'genotyping',
  вирус: 'virus',
  сальмонеллёз: 'salmonellosis',
  хламидия: 'chlamydia',
  пневмония: 'pneumonia',
  бруцеллез: 'brucellosis',
  краснухе: 'rubella',
  токоплазме: 'toxoplasma',
  токсоплазме: 'toxoplasma',
  площадь: 'area',
  зон: 'zone',
  упаковка: 'pack',
  упаковки: 'pack',
  флакон: 'vial',
  тюбик: 'tube',
  мл: 'ml',
  мг: 'mg',
  таблетки: 'tablets',
  капсулы: 'capsules',
  крем: 'cream',
  гель: 'gel',
  сыворотка: 'serum',
  шампунь: 'shampoo',
  маска: 'mask',
  тоник: 'tonic',
  молочко: 'lotion',
  очищающий: 'cleansing',
  очищающее: 'cleansing',
  увлажняющий: 'moisturizing',
  восстанавливающий: 'restoring',
  защитный: 'protective',
  солнцезащитный: 'sunscreen',
  дневной: 'day',
  ночной: 'night',
  универсальный: 'universal',
  набор: 'set',
  комплекс: 'complex',
  курс: 'course',
  межбровье: 'glabella',
  титановая: 'titanium',
  нить: 'thread',
  дарсонваль: 'Darsonval',
  бальзам: 'balm',
  для: 'for',
  чувствительной: 'sensitive',
  чувствительная: 'sensitive',
  размером: 'sized',
  ладонь: 'palm',
  одна: 'one',
  вуаль: 'veil',
  спрей: 'spray',
  тела: 'body',
  сканирование: 'scanning',
  аппарате: 'device',
  дня: 'days',
  дней: 'days',
  внутренне: 'internal',
  очаговая: 'focal',
  иммунокриохирургия: 'immunocryosurgery',
  подногтевые: 'subungual',
  бородавки: 'warts',
  родинок: 'moles',
  трансплантация: 'transplantation',
  меланоцитов: 'melanocytes',
  трихолога: 'trichologist',
  дерматовениролога: 'dermatovenereologist',
  дерматоонколога: 'dermo-oncologist',
  дерматокосметолога: 'dermatocosmetologist',
  подолога: 'podiatrist',
  трихоскопия: 'trichoscopy',
  дерматоскопия: 'dermatoscopy',
  капельница: 'IV drip',
  глубоких: 'deep',
  поверхностных: 'superficial',
  контактным: 'contact',
  красноты: 'redness',
  аллергопроба: 'allergy test',
  пунктов: 'points',
  метотриксатом: 'methotrexate',
  обработка: 'treatment',
  учета: 'cost of',
  учетом: 'including cost of',
  лекарственных: 'medication',
  препаратов: 'drugs',
  раны: 'wound',
  похудения: 'weight loss',
  франция: 'France',
  база: 'database',
  данных: 'data',
  трихопигментация: 'trichopigmentation',
  голова: 'scalp',
  аппаратная: 'device-based',
  стопы: 'foot',
  мозоли: 'callus',
  стерженя: 'without core',
  стерженем: 'with core',
  вросшего: 'ingrown',
  омоложение: 'rejuvenation',
  глаз: 'eyes',
  вокруг: 'around',
  влок: 'IVL',
  аппарат: 'device',
  внутривенное: 'intravenous',
  облучение: 'irradiation',
  против: 'anti-',
  гиалу: 'Hyalu',
  флюид: 'fluid',
  очень: 'very',
  сухой: 'dry',
  сухих: 'dry',
  лосьон: 'lotion',
  несовершенств: 'blemishes',
  цераве: 'CeraVe',
  нормальной: 'normal',
  нормальных: 'normal',
  жирных: 'oily',
  ана: 'AHA',
  вна: 'BHA',
  кислотами: 'acids',
  аминексил: 'Aminexil',
  средство: 'product',
  женщин: 'women',
  мужчин: 'men',
  монодоза: 'single-dose',
  энерджи: 'Energy',
  выпадения: 'hair loss',
  тонизирующий: 'tonifying',
  кондиционер: 'conditioner',
  перхоти: 'dandruff',
  пехоти: 'dandruff',
  псолюшн: 'Solution',
  кераторегулирующий: 'kerato-regulating',
  головы: 'scalp',
  регулир: 'regulating',
  успокаивающий: 'soothing',
  термальная: 'thermal',
  вода: 'water',
  виши: 'Vichy',
  минерал: 'Mineral',
  хгч: 'hCG',
  холестерин: 'cholesterol',
  общ: 'total',
  общий: 'total',
  стаканная: 'glass',
  мочи: 'urine',
  моче: 'urine',
  нативный: 'native',
  мазок: 'smear',
  трихомониаз: 'trichomoniasis',
  лептотрихоз: 'leptotrichosis',
  волосистой: 'hairy',
  дыхательно: 'breath',
  уреазный: 'urease',
  определение: 'detection',
  тимоловая: 'thymol',
  высокой: 'high',
  плотности: 'density',
  низкой: 'low',
  холинэстераза: 'cholinesterase',
  хлориды: 'chlorides',
  мозговой: 'brain',
  натрийуретический: 'natriuretic',
  пептид: 'peptide',
  ранняя: 'early',
  диагностика: 'diagnosis',
  беременности: 'pregnancy',
  точное: 'precise',
  разведение: 'dilution',
  проба: 'test',
  антиспермальные: 'antisperm',
  шуварского: 'Shwartzman',
  симса: 'Sims',
  гунера: 'Gunner',
  хг: 'hCG',
  кожей: 'skin',
  интенсивное: 'intensive',
  увлажнение: 'hydration',
  лрп: 'LRP',
  лр: 'LRP',
  спф: 'SPF',
  со: 'with',
  без: 'without',
  расходного: 'consumable',
  расходных: 'consumable',
  материала: 'materials',
  материалов: 'materials',
  татуаж: 'permanent makeup',
  татуажа: 'permanent makeup',
  розацеа: 'rosacea',
  механическая: 'manual',
  ультразвуковая: 'ultrasonic',
  чистка: 'cleansing',
  уход: 'care',
  обш: 'total',
  к: 'to',
  свобод: 'free',
  хорионич: 'chorionic',
  гонадотропин: 'gonadotropin',
  нейрон: 'neuron',
  специфическая: 'specific',
  енолаза: 'enolase',
  лёгкие: 'lungs',
  хорионический: 'chorionic',
  яички: 'testicles',
  пуз: 'ectopic',
  занос: 'pregnancy',
  простатспецифический: 'prostate-specific',
  антиген: 'antigen',
  антигену: 'antigen',
  трихомонада: 'trichomonad',
  митохондриям: 'mitochondria',
  одноцепочечной: 'single-stranded',
  двухцепочечной: 'double-stranded',
  днк: 'DNA',
  эхинококку: 'echinococcus',
  гельминты: 'helminths',
  токсокароз: 'toxocariasis',
  описторхоз: 'opisthorchiasis',
  трихенеллёз: 'trichinellosis',
  эхинококкоз: 'echinococcosis',
  поверхностному: 'surface',
  вирусу: 'virus',
  хламидиям: 'chlamydia',
  трихомонаде: 'trichomonas',
  пневм: 'pneumoniae',
  точек: 'sites',
  уха: 'urine',
  неинвазивное: 'non-invasive',
  пола: 'fetal sex',
  плода: 'fetus',
  определние: 'assessment',
  риска: 'risk',
  развития: 'development',
  аномалий: 'anomalies',
  хромосомного: 'chromosomal',
  набора: 'set',
  экспертный: 'expert',
  точность: 'accuracy',
  иммуногенетика: 'immunogenetics',
  прогнозе: 'prognosis',
  противовирусной: 'antiviral',
  терапии: 'therapy',
  при: 'for',
  вгс: 'HCV',
  токсоплазма: 'toxoplasma',
  цмв: 'CMV',
  хламадия: 'chlamydia',
  микоплазма: 'mycoplasma',
  уреоплазма: 'ureaplasma',
  рубелла: 'rubella',
  герпес: 'herpes',
  тип: 'type',
  маркер: 'marker',
  гастроинестинальных: 'gastrointestinal',
  первую: 'primarily',
  очередь: '',
  желудочной: 'gastric',
  железы: 'gland',
  рецептр: 'receptor',
  из: 'of',
  наиболее: 'most',
  значимых: 'significant',
  молекулярных: 'molecular',
  маркеров: 'markers',
  раке: 'cancer',
  молочной: 'breast',
  зелёз: 'glands',
  прогастрин: 'progastrin',
  высвобождающий: 'releasing',
  белок: 'protein',
  высокочувствительных: 'high-sensitivity',
  мелкоклеточного: 'small cell',
  рака: 'cancer',
  лёгких: 'lung',
  скрин: 'screen',
  микоз: 'mycosis',
  выявление: 'detection',
  типирование: 'typing',
  возбудителей: 'pathogens',
  грибковых: 'fungal',
  инфекций: 'infections',
};

const EXACT_EN_MAP: Record<string, string> = {
  ...(exactEn as Record<string, string>),
};

const SORTED_EXACT_PHRASES = [...EXACT_PHRASES_EN].sort((a, b) => b[0].length - a[0].length);

function normalizeKey(text: string): string {
  return text.toLowerCase().replace(/ё/g, 'е').replace(/\s+/g, ' ').trim();
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function applyBoundaryPhrases(text: string, phrases: [string, string][]): string {
  let result = text;
  for (const [from, to] of phrases) {
    const pattern = new RegExp(
      `(?<![\\p{L}\\p{N}])${escapeRegExp(from)}(?![\\p{L}\\p{N}])`,
      'giu',
    );
    result = result.replace(pattern, to);
  }
  return result;
}

function tokenizeRussian(text: string): string[] {
  const tokens: string[] = [];
  let current = '';
  let mode: 'cyr' | 'lat' | 'other' = 'other';

  const flush = () => {
    if (current) tokens.push(current);
    current = '';
  };

  for (const char of text) {
    if (/[а-яА-ЯёЁ]/.test(char)) {
      if (mode !== 'cyr') flush();
      mode = 'cyr';
      current += char;
    } else if (/[a-zA-Z0-9]/.test(char)) {
      if (mode !== 'lat') flush();
      mode = 'lat';
      current += char;
    } else {
      flush();
      mode = 'other';
      tokens.push(char);
    }
  }
  flush();
  return tokens;
}

function translateToken(token: string): string {
  if (!token || !/[а-яА-ЯёЁ]/.test(token)) return token;

  const lower = token.toLowerCase();
  const mapped = WORDS_EN[lower];
  if (mapped !== undefined) {
    if (!mapped) return '';
    const isCapital = token[0] === token[0].toUpperCase() && token[0] !== token[0].toLowerCase();
    if (!isCapital) return mapped;
    return mapped.charAt(0).toUpperCase() + mapped.slice(1);
  }

  return transliterateToken(token);
}

function transliterateToken(token: string): string {
  const map: Record<string, string> = {
    а: 'a', б: 'b', в: 'v', г: 'g', д: 'd', е: 'e', ё: 'yo', ж: 'zh',
    з: 'z', и: 'i', й: 'y', к: 'k', л: 'l', м: 'm', н: 'n', о: 'o',
    п: 'p', р: 'r', с: 's', т: 't', у: 'u', ф: 'f', х: 'kh', ц: 'ts',
    ч: 'ch', ш: 'sh', щ: 'shch', ъ: '', ы: 'y', ь: '', э: 'e', ю: 'yu', я: 'ya',
  };
  return token
    .split('')
    .map((char) => {
      const lower = char.toLowerCase();
      const tr = map[lower];
      if (!tr) return char;
      return char === lower ? tr : tr.charAt(0).toUpperCase() + tr.slice(1);
    })
    .join('');
}

function finalizeCyrillic(text: string): string {
  if (!/[а-яА-ЯёЁ]/.test(text)) return text;
  return text.replace(/[\p{Script=Cyrillic}]+/gu, (run) =>
    tokenizeRussian(run).map((t) => translateToken(t)).join(' '),
  );
}

function applyPreprocess(text: string): string {
  return text
    .replace(/в\/в/gi, 'IV')
    .replace(/в\/м/gi, 'IM')
    .replace(/(\d)\s*х\s*(\d)/gi, '$1×$2');
}

function cleanupEn(text: string): string {
  return text
    .replace(/\u044C/g, '')
    .replace(/\u044A/g, '')
    .replace(/\s+([,.;:!?])/g, '$1')
    .replace(/\(\s+/g, '(')
    .replace(/\s+\)/g, ')')
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+,/g, ',')
    .replace(/,\s*/g, ', ')
    .replace(/\bTreatment (acne.+)$/i, '$1 treatment')
    .replace(/^Removal ([a-z].+)$/i, '$1 removal')
    .replace(/^Collection blood$/i, 'Blood collection')
    .replace(/\banti- ([a-z])/gi, 'anti-$1')
    .trim();
}

function capitalizeSentence(text: string): string {
  const trimmed = text.trim();
  if (!trimmed) return trimmed;
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
}

export function translatePriceRuToEn(
  nameRu: string,
  options?: { skipCache?: boolean },
): string {
  const normalized = normalizePriceRu(nameRu.trim());
  if (!normalized) return '';

  const exactKey = normalizeKey(normalized);
  if (!options?.skipCache) {
    const cached = EXACT_EN_MAP[exactKey];
    if (cached && !/[а-яА-ЯёЁ]/.test(cached)) return cached;
  }

  let text = applyBoundaryPhrases(normalized, SORTED_EXACT_PHRASES);
  text = applyPreprocess(text);

  const tokens = tokenizeRussian(text);
  const translated = tokens.map((token) => {
    if (!/[а-яА-ЯёЁ]/.test(token)) return token;
    return translateToken(token);
  });

  return capitalizeSentence(cleanupEn(finalizeCyrillic(translated.join(''))));
}
