import { ARTICLES } from '../data';
import { ARTICLE_ROUTE_REDIRECTS } from '../utils/articles';
import { isApiArticleId } from '../utils/articleViews';
import type { Locale } from '../types';

export const ARTICLE_REDIRECT_LOCALES: Locale[] = ['uz', 'ru', 'en'];

export type ArticleRedirectPair = {
  from: string;
  to: string;
};

type ApiArticleListItem = {
  id: string;
  slug: string;
};

/** Resolve canonical public route key for a slug or legacy alias. */
export function resolveCanonicalArticleRouteKey(slugOrKey: string): string | null {
  const retired = ARTICLE_ROUTE_REDIRECTS[slugOrKey];
  if (retired) return retired;

  const staticById = ARTICLES.find((item) => item.id === slugOrKey);
  if (staticById) return staticById.id;

  const staticBySlug = ARTICLES.find((item) => item.slug === slugOrKey);
  if (staticBySlug) return staticBySlug.id;

  return null;
}

function articlePath(locale: Locale, segment: string): string {
  return `/${locale}/articles/${segment}`;
}

function addPair(pairs: Map<string, string>, from: string, to: string): void {
  if (!from || !to || from === to) return;
  pairs.set(from, to);
}

function addLocaleVariants(
  pairs: Map<string, string>,
  segment: string,
  targetRouteKey: string,
): void {
  for (const locale of ARTICLE_REDIRECT_LOCALES) {
    addPair(pairs, articlePath(locale, segment), articlePath(locale, targetRouteKey));
    addPair(
      pairs,
      `${articlePath(locale, segment)}/`,
      articlePath(locale, targetRouteKey),
    );
  }
}

/** Build 301 redirect map: legacy slug / UUID / retired route -> canonical art-* URL. */
export function buildArticleRedirectPairs(apiArticles: ApiArticleListItem[] = []): ArticleRedirectPair[] {
  const pairs = new Map<string, string>();

  for (const [from, to] of Object.entries(ARTICLE_ROUTE_REDIRECTS)) {
    addLocaleVariants(pairs, from, to);
  }

  for (const article of ARTICLES) {
    const routeKey = article.id;
    if (article.slug !== routeKey) {
      addLocaleVariants(pairs, article.slug, routeKey);
    }
  }

  const slugToRoute = new Map<string, string>();
  for (const article of ARTICLES) {
    slugToRoute.set(article.slug, article.id);
  }

  for (const apiArticle of apiArticles) {
    const bySlug = slugToRoute.get(apiArticle.slug);
    const canonical = bySlug
      ? resolveCanonicalArticleRouteKey(bySlug) ?? bySlug
      : resolveCanonicalArticleRouteKey(apiArticle.slug);

    if (!canonical) continue;

    if (isApiArticleId(apiArticle.id)) {
      addLocaleVariants(pairs, apiArticle.id, canonical);
    }

    if (apiArticle.slug !== canonical) {
      addLocaleVariants(pairs, apiArticle.slug, canonical);
    }
  }

  /** Known API duplicate not in static catalog. */
  addLocaleVariants(pairs, 'postakne-chandiq-va-doglarni-kamaytirish', 'art-postakne');
  addLocaleVariants(pairs, '52ef2318-aa9d-4b80-a558-8c3140781f14', 'art-postakne');

  return [...pairs.entries()]
    .map(([from, to]) => ({ from, to }))
    .sort((a, b) => a.from.localeCompare(b.from));
}

export function buildNginxArticleRedirectMap(pairs: ArticleRedirectPair[]): string {
  const lines = [
    '# Generated by scripts/generateArticleNginxRedirects.ts — do not edit manually.',
    'map $uri $radeski_article_redirect {',
    '    default "";',
  ];

  for (const { from, to } of pairs) {
    lines.push(`    ${from} ${to};`);
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}
