/**
 * Builds src/data/articleIndex.generated.ts — the lightweight article data the main bundle
 * needs for cards, lists and SEO (titles, summaries, tags, reading-time word counts).
 *
 * The full article bodies (~1 MB of text) stay in src/data/articles/* and only load with the
 * article page, instead of shipping with every page of the site.
 *
 * Run after editing anything in src/data/articles (the build runs it automatically):
 *   npx tsx scripts/buildArticleIndex.ts
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { ARTICLE_RICH_CATALOG } from '../src/data/articleRichCatalog';
import { STATIC_ARTICLE_SOURCES } from '../src/data/staticArticleSources';
import { stripArticleHashtagSection } from '../src/utils/articleContent';
import type { Locale } from '../src/types';

const LOCALES: Locale[] = ['uz', 'ru', 'en'];
const OUTPUT = path.resolve(import.meta.dirname, '../src/data/articleIndex.generated.ts');

function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

const catalogLight: Record<string, Record<Locale, unknown>> = {};
for (const [key, catalog] of Object.entries(ARTICLE_RICH_CATALOG)) {
  const perLocale = {} as Record<Locale, unknown>;
  for (const locale of LOCALES) {
    const entry = catalog[locale];
    const body = entry?.body?.trim() || '';
    perLocale[locale] = {
      summary: entry?.summary?.trim() || '',
      tags: entry?.tags ?? [],
      bodyLength: body.length,
      bodyWords: countWords(stripArticleHashtagSection(body)),
    };
  }
  catalogLight[key] = perLocale;
}

// Cards only — the body comes from the catalog (see resolveArticleBody), so drop the preview.
const staticArticles = STATIC_ARTICLE_SOURCES.map((article) => ({
  ...article,
  content: { uz: '', ru: '', en: '' },
}));

const source = `// AUTO-GENERATED by scripts/buildArticleIndex.ts — do not edit by hand.
import type { Article, Locale } from '../types';

export interface ArticleCatalogLight {
  summary: string;
  tags: string[];
  /** Length of the full catalog body (decides catalog vs API text, like resolveArticleBody). */
  bodyLength: number;
  /** Words in the body without its hashtag block (for reading time). */
  bodyWords: number;
}

export const ARTICLE_CATALOG_LIGHT: Record<string, Record<Locale, ArticleCatalogLight>> = ${JSON.stringify(catalogLight, null, 2)};

export const STATIC_ARTICLES: Article[] = ${JSON.stringify(staticArticles, null, 2)};
`;

writeFileSync(OUTPUT, source, 'utf8');
console.log(
  `[article-index] ${Object.keys(catalogLight).length} catalog entries, ${staticArticles.length} articles -> ${path.relative(process.cwd(), OUTPUT)} (${Math.round(Buffer.byteLength(source) / 1024)} KB)`,
);
