/**
 * Laboratoriya bo'limidagi barcha 466 ta nom uchun aniq o'zbek tarjimalarini generatsiya qiladi.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const ruList = JSON.parse(fs.readFileSync(path.join(__dirname, 'lab-ru-list.json'), 'utf8'));

/** So'z / ibora lug'ati (kichik harf) */
const W = {
  альбумин: 'Albumin',
  железа: 'temir',
  железо: 'temir',
  кровь: 'qon',
  крови: 'qon',
  инсулин: 'Insulin',
  калий: 'Kaliy',
  кальций: 'Kalsiy',
  магний: 'Magniy',
  мочевина: 'Mochevina',
  креатинин: 'Kreatinin',
  кортизол: 'Kortizol',
  пролактин: 'Prolaktin',
  тестостерон: 'Testosteron',
  ферритин: 'Ferritin',
  ренин: 'Renin',
  ревматоидный: 'revmatoid',
  фактор: 'faktor',
  тиреотропный: 'tirotrop',
  гармон: 'gormon',
  трийодтрионин: 'trijodtironin',
  трийодтиронин: 'trijodtironin',
  триоксин: 'trijodtironin',
  тироксин: 'tiroksin',
  свободный: 'erkin',
  свобод: 'erkin',
  общий: 'umumiy',
  общая: 'umumiy',
  общее: 'umumiy',
  обший: 'umumiy',
  холестерин: 'xolesterin',
  биопсия: 'Biopsiya',
  лактатдегидрогеназа: 'laktatdegidrogenaza',
  антитела: 'antitanalar',
  антител: 'antitanalar',
  тиреоглобулину: 'tireoglobulin',
  териопироксидазе: 'tireoperoksidaza',
  бак: 'bakteriologik',
  исследование: 'tekshiruv',
  иследование: 'tekshiruv',
  слизистой: 'shilliq',
  оболочки: 'qavat',
  из: '',
  зева: 'tomoqdan',
  гистологическое: 'gistologik',
  лейкоформулы: 'leykotsit formulasisiz',
  тромбоциты: 'trombotsitlar',
  скорость: 'tezligi',
  оседания: 'cho\'kish',
  эритроцитов: 'eritrotsitlar',
  эозинофилы: 'eozinofillar',
  концентрация: 'konsentratsiyasi',
  гемоглобина: 'gemoglobin',
  группа: 'guruh',
  резус: 'rezus',
  стаканная: 'stakanga',
  проба: 'proba',
  нечипоренко: 'Nechiporenko',
  зимницкому: 'Zimnitskiy',
  желчные: 'o\'t',
  пигменты: 'pigmentlari',
  ацетон: 'atseton',
  микроальбумин: 'mikroalbumin',
  белок: 'belok',
  моче: 'siydikda',
  мочи: 'siydik',
  моча: 'siydik',
  цитология: 'tsitologiya',
  осадка: 'cho\'kindisi',
  мазок: 'surtma',
  мазка: 'surtmasi',
  флору: 'flora',
  атипические: 'atipik',
  клетки: 'hujayralar',
  спермограмма: 'Spermogramma',
  сок: 'soki',
  простаты: 'prostata',
  нативный: 'native',
  трихомониаз: 'trixomoniyaz',
  женский: 'ayollar',
  лептотрихоз: 'leptotriks',
  мокроты: 'balg\'am',
  назальный: 'burun',
  секрет: 'sekret',
  чесоточный: 'qichishcha',
  клещ: 'kana',
  лейшманиоз: 'Leyshmanioz',
  совместимость: 'moslik',
  курцрока: 'Kurtsrok',
  миллера: 'Miller',
  шуварского: 'Shuvarskiy',
  симса: 'Sims',
  гунера: 'Gunera',
  антиспермальные: 'antisperm',
  энтеробиоз: 'enterobioz',
  острицы: 'kaltakesaklar',
  свертываемости: 'ivish',
  длительность: 'davomiyligi',
  кровотечения: 'qon ketishi',
  протромбиновое: 'protrombin',
  время: 'vaqti',
  тромбо: 'trombo',
  динамика: 'dinamikasi',
  фибриноген: 'Fibrinogen',
  коалиновое: 'kaolin',
  тромбиновое: 'trombin',
  димер: 'dimer',
  антитромбин: 'Antitrombin',
  волчаночный: 'SLE',
  антикоагулянт: 'antikoagulyant',
  подтверждающий: 'tasdiqlovchi',
  скрининг: 'skrining',
  бруцеллёз: 'Brutsellez',
  бруцеллез: 'Brutsellez',
  тропонин: 'Troponin',
  глюкозо: 'glukoza',
  толерантный: 'tolerantlik',
  тест: 'testi',
  акция: 'AKSIYA',
  фруктозамин: 'Fruktozamin',
  билирубин: 'bilirubin',
  прямой: 'to\'g\'ridan-to\'g\'ri',
  трансаминаза: 'transaminaza',
  тимоловая: 'timol',
  желчные: 'o\'t',
  кислоты: 'kislotalari',
  триглицериды: 'triglitseridlar',
  аполипопротеин: 'apolipoprotein',
  железосвязывающая: 'temir bog\'lovchi',
  способность: 'qobiliyati',
  трансферрин: 'Transferrin',
  эритропоэтин: 'Eritropoetin',
  альфа: 'alfa',
  амилаза: 'amilaza',
  диастаза: 'diastaza',
  липаза: 'Lipaza',
  щелочная: 'ishqoriy',
  фосфатаза: 'fosfataza',
  кислая: 'kislo',
  лактодегидрогеназа: 'laktatdegidrogenaza',
  холинэстераза: 'Xolinesteraza',
  гамма: 'gamma',
  глютамилтрансфераза: 'glyutamiltransferaza',
  креатининкиназа: 'kreatinkinaza',
  цистатин: 'Tsistatin',
  глюкоматдекарбоксилаза: 'glyukomatdekarboksilaza',
  эластаза: 'Elastaza',
  кальпротектин: 'Kalprotektin',
  реберга: 'Reberg',
  мочевая: 'mochevina',
  кислота: 'kislota',
  суточной: 'sutkalik',
  натрий: 'Natriy',
  хлориды: 'Xloridlar',
  фосфор: 'Fosfor',
  медь: 'Mis',
  цинк: 'Rux',
  витамин: 'vitamin',
  фолиевая: 'foliy',
  гомоцистеин: 'Gomotsistein',
  реактивный: 'reaktiv',
  циклическому: 'tsiklik',
  цитруллин: 'tsitrullin',
  миоглобин: 'Mioglobin',
  прокальцитонин: 'Prokalsitonin',
  остеокальцин: 'Osteokalsin',
  кальцитонин: 'Kalsitonin',
  мозговой: 'miya',
  натрийуретический: 'natriyuretik',
  пептид: 'peptid',
  прогестерон: 'Progesteron',
  эстрадиол: 'Estradiol',
  эстриол: 'Estriol',
  фоликулостимулирующий: 'follikulostimulyatsiya',
  лютеинизирующий: 'lyuteinizatsiya',
  дегидроэпиандростерон: 'degidroepiandrosteron',
  сульфат: 'sulfat',
  антимюллеров: 'antimyuller',
  глобулин: 'globulin',
  связывающий: 'bog\'lovchi',
  половые: 'jinsiy',
  гормоны: 'gormonlar',
  ингибин: 'Ingibin',
  утро: 'ertalab',
  вечер: 'kechqurun',
  соматотропный: 'somatotrop',
  инсулиноподобный: 'insulinga o\'xshash',
  роста: 'o\'sish',
  фактор: 'faktor',
  протеин: 'protein',
  адренокортикотропный: 'adrenokortikotrop',
  альдостерон: 'Aldosteron',
  адреналин: 'Adrenalin',
  норадреналин: 'Noradrenalin',
  паратгормон: 'Paratgormon',
  ранняя: 'erta',
  диагностика: 'aniqlash',
  беременности: 'homiladorlik',
  точное: 'aniq',
  разведение: 'suyultirish',
  алфа: 'alfa',
  фетопротеин: 'fetoprotein',
  хорионич: 'xorionik',
  гонадотропин: 'gonadotropin',
  плазмы: 'plazma',
  ассоциированный: 'assotsiatsiyalangan',
  раковый: 'saraton',
  эмбриональный: 'embrional',
  антиген: 'antigen',
  углеводный: 'uglevod',
  молочная: 'sut',
  поджелудочная: 'oshqozon osti',
  желудок: 'oshqozon',
  яичники: 'tuxumdonlar',
  нейрон: 'neyron',
  специфическая: 'spetsifik',
  енолаза: 'enolaza',
  лёгкие: 'o\'pka',
  легкие: 'o\'pka',
  печень: 'jigar',
  яички: 'moya',
  пуз: 'qorin',
  занос: 'ko\'chirish',
  простатспецифический: 'prostata-spetsifik',
  свобод: 'erkin',
  индекс: 'indeks',
  плоскоклеточной: 'tekis hujayrali',
  карциномы: 'kartsinoma',
  щитовидная: 'qalqonsimon',
  маркер: 'marker',
  потенциального: 'potentsial',
  повреждения: 'zararlanish',
  микоплазма: 'Mikoplazma',
  уреаплазма: 'Ureaplazma',
  гонококк: 'Gonokokk',
  трихомонада: 'Trixomonada',
  гарднерелла: 'Gardnerella',
  цитомегаловирус: 'Sitomegalovirus',
  простого: 'oddiy',
  герпеса: 'herpes',
  качество: 'sifat',
  количество: 'miqdor',
  пептид: 'peptid',
  аллергопанели: 'Allergopanel',
  смешанная: 'aralash',
  ингаляционна: 'ingalyatsion',
  пищевая: 'oziq-ovqat',
  антинуклеарные: 'antinuklear',
  антиспермальные: 'antisperm',
  фосфолипидам: 'fosfolipid',
  митохондриям: 'mitoxondriya',
  миелопероксидазе: 'mieloperoksidaza',
  модифицированному: 'modifikatsiyalangan',
  цитруллинированому: 'tsitrullinlangan',
  виментину: 'vimentin',
  целиакия: 'Tseliakiya',
  трансглутаминаза: 'transglutaminaza',
  глиадину: 'gliadin',
  количественный: 'miqdoriy',
  одноцепочечной: 'bir zanjirli',
  двухцепочечной: 'ikki zanjirli',
  определение: 'aniqlash',
  гистонам: 'giston',
  протеиназе: 'proteinaza',
  аутоиммунная: 'autoimmun',
  панель: 'panel',
  антигенов: 'antigenlar',
  антинейтрофильные: 'antineytrafil',
  цитоплазматические: 'sitoplazmatik',
  интерлейкин: 'Interleykin',
  компонент: 'Komponent',
  комплемента: 'komplement',
  лямблиям: 'lambliya',
  суммарные: 'umumiy',
  аскаридам: 'askariid',
  эхинококку: 'exinokokk',
  гельминты: 'Gelmintlar',
  токсокароз: 'toksokaroz',
  описторхоз: 'opistorxoz',
  трихенеллёз: 'trixineloz',
  эхинококкоз: 'exinokokkoz',
  поверхностному: 'yuzaki',
  ядерному: 'yadro',
  оболочки: 'qobiq',
  гепатита: 'gepatit',
  токсоплазме: 'toksoplazma',
  вирусу: 'virus',
  краснухи: 'qizamiq',
  хламидиям: 'xlamidiya',
  микоплазме: 'mikoplazma',
  уреаплазме: 'ureaplazma',
  гарднерелле: 'gardnerella',
  трихомонаде: 'trixomonada',
  кандиде: 'kandida',
  пневм: 'o\'pka',
  суммарные: 'umumiy',
  эпштейн: 'Epstein',
  барра: 'Barr',
  раннему: 'erta',
  ядерному: 'yadro',
  корь: 'Qizilcha',
  коклюш: 'Koklyush',
  туберкулёз: 'Sil kasalligi',
  туберкулез: 'Sil kasalligi',
  сальмонеллёз: 'Salmonellyoz',
  хламидия: 'Xlamidiya',
  пневмония: 'pnevmoniya',
  рецепторам: 'retseptorlar',
  скрингенетика: 'Skrining-genetika',
  метаболизма: 'metabolizm',
  фолатов: 'folat',
  онкогенетика: 'Onko-genetika',
  гипертонической: 'gipertoniya',
  болезни: 'kasalligi',
  азооспермии: 'azoospermiya',
  мужское: 'erkak',
  бесплодие: 'bepushtlik',
  делеции: 'Deletsiya',
  локуса: 'lokus',
  муковисцидоза: 'mukovistsidoz',
  мутации: 'Mutatsiya',
  генетика: 'Genetika',
  синдрома: 'sindrom',
  жельбера: 'Jelber',
  полиморфизма: 'polimorfizm',
  отцовство: 'otalik',
  материнство: 'onalik',
  маркеров: 'marker',
  кариотип: 'Kariotip',
  экспертного: 'ekspert',
  уровня: 'darajasi',
  неинвазивное: 'Invaziv bo\'lmagan',
  пола: 'jinsi',
  плода: 'homila',
  точность: 'aniqlik',
  определние: 'aniqlash',
  риска: 'xavfi',
  развития: 'rivojlanishi',
  аномалий: 'anomaliyalar',
  хромосомного: 'xromosom',
  набора: 'to\'plami',
  экспертный: 'ekspert',
  иммуногенетика: 'Immunogenetika',
  прогнозе: 'prognoz',
  противовирусной: 'antiviral',
  терапии: 'terapiya',
  выделение: 'DNK ajratish',
  нестандартного: 'nostandart',
  образца: 'namunadan',
  кардио: 'Kardio',
  тромбофилия: 'trombofiliya',
  такролимус: 'Takrolimus',
  гастроинестинальных: 'gastrointestinal',
  новообразования: 'o\'smalar',
  первую: 'birinchi',
  очередь: 'navbatda',
  желудочной: 'oshqozon',
  прогастрин: 'progastrin',
  высвобождающий: 'ajratuvchi',
  высокочувствительных: 'yuqori sezgir',
  мелкоклеточного: 'mayda hujayrali',
  рака: 'saraton',
  медулярный: 'medullyar',
  щитовидной: 'qalqonsimon',
  человека: 'inson',
  тип: 'tip',
  пап: 'PAP',
  соскоба: 'surtma',
  матки: 'bachadon',
  хламидия: 'Xlamidiya',
  конъюнктивы: 'kon\'yunktiva',
  уха: 'quloq',
  участка: 'zararlangan',
  поражения: 'hudud',
  плевральная: 'plevra',
  жидкость: 'suyuqlik',
  спинномозговая: 'orqa miya',
  дизбактериоз: 'disbakterioz',
  кишечная: 'ichak',
  дизентерия: 'dizenteriya',
  сальмонелез: 'salmonelez',
  стафилококк: 'stafilokokk',
  точек: 'nuqta',
  спермы: 'sperma',
  грудное: 'ko\'krak',
  молоко: 'suti',
  стерильность: 'sterillik',
  аскарида: 'Askariid',
  коагулограмма: 'Koagulogramma',
  копрология: 'Koproskopiya',
  демодекоз: 'Demodekoz',
  грибы: 'zamburug\'',
  грибок: 'zamburug\'',
  чесотки: 'qichishcha',
  лямблии: 'lambliyalar',
  простейшие: 'oddiy bir hujayralilar',
  гельминтов: 'gelmint tuxumlari',
  скрытую: 'yashirin',
  кровь: 'qon',
  кал: 'kal',
  кала: 'kal',
  копрограмма: 'Koprogramma',
  волосистой: 'sochli',
  части: 'qismi',
  головы: 'bosh',
  гладкой: 'silliq',
  кожи: 'teri',
  ногтей: 'tirnoq',
  руки: 'qo\'l',
  уретры: 'uretra',
  rh: 'Rh',
  фактору: 'faktor',
  фактор: 'faktor',
  качественный: 'sifatli',
  количественный: 'miqdoriy',
  генотипирование: 'genotiplashtirish',
  слюна: 'tupruk',
  слюны: 'tupruk',
  желудочный: 'oshqozon',
  сок: 'soki',
  коронавирусу: 'koronavirus',
  антитела: 'antitanalar',
  краснухе: 'qizamiq',
  впр: 'VPG',
  цмв: 'TsMV',
  впг: 'VPG',
  токсоплазме: 'toksoplazma',
  гепатит: 'gepatit',
  сифилис: 'sifilis',
  вич: 'VICh',
  иностранцам: 'chet elliklar uchun',
  экспресс: 'ekspress',
  антиген: 'antigen',
  дыхательно: 'nafas',
  уреазный: 'ureaza',
  определение: 'aniqlash',
  helicobacter: 'Helicobacter',
  pylory: 'pylori',
  pylori: 'pylori',
  rose: 'Rose',
  bengal: 'Bengal',
  остр: 'o\'tkir',
  респираторные: 'respirator',
  заболевания: 'kasalliklar',
  выявление: 'aniqlash',
  типирование: 'tipizatsiya',
  возбудителей: 'qo\'zg\'atolchilar',
  грибковых: 'zamburug\'',
  инфекций: 'infeksiyalar',
  резистентности: 'chidamlilik',
  антибиотикам: 'antibiotiklar',
  фемофлор: 'Femoflor',
  скрин: 'skrining',
  андрофлор: 'Androflor',
  комплекс: 'Kompleks',
  электролитов: 'elektrolitlar',
  группа: 'guruh',
  комплекс: 'Kompleks',
};

/** To'liq aniq tarjimalar — ustuvor */
const EXACT = {
  '17-ОН Прогестерон': '17-OH progesteron',
  'Cytomegalovirus (ЦМВ) IgG': 'Sitomegalovirus (TsMV) IgG',
  'DHEA-S': 'DHEA-S',
  'HBsAg (гепатит В)': 'HBsAg (B gepatiti)',
  'HVC (гепатит С)': 'HCV (C gepatiti)',
  'HIV (ВИЧ)': 'HIV (OITS)',
  'RW (сифилис)': 'RW (sifilis)',
  'АКТГ': 'AKTG',
  'Аланинаминотрансфераза (АЛТ)': 'ALT (alanin aminotransferaza)',
  'Альбумин': 'Albumin',
  'Антистрептолизин АСЛО': 'ASLO (antistreptolizin-O)',
  'Аскарида': 'Askariid',
  'Аспартатаминотрасфераза (АСТ)': 'AST (aspartat aminotransferaza)',
  'АТ к ТПО': 'AT k TPO',
  'Общий Билирубин': 'Umumiy bilirubin',
  'Витамин Д3': 'D3 vitamini',
  'Герпес Herpes Simplex 1/2 IgG': 'Herpes Simplex 1/2 IgG',
  'Гликозированный гемоглобин': 'Glikozillangan gemoglobin (HbA1c)',
  'Глюкоза': 'Qondagi glukoza',
  'Железа (Кровь)': 'Temir (qon)',
  'Инсулин': 'Insulin',
  'Калий': 'Kaliy',
  'Кальций': 'Kalsiy',
  'Коагулограмма': 'Koagulogramma (qon ivishini tekshirish)',
  'Копрология': 'Koproskopiya (kal tahlili)',
  'Кортизол': 'Kortizol',
  'Креатинин': 'Kreatinin',
  'ЛГ': 'LG',
  'Магний': 'Magniy',
  'Мазок из уретры': 'Uretra surtmasi',
  'Мочевина': 'Mochevina',
  'Общий анализ крови (развернутый)': 'Qonning kengaytirilgan umumiy tahlili',
  'Общий анализ мочи': 'Siydikning umumiy tahlili',
  'Общий белок': 'Umumiy belok',
  'Пролактин': 'Prolaktin',
  'Ревматоидный фактор': 'Revmatoid faktor',
  'С реактивный белок': 'C-reaktiv belok',
  'Соскоб на грибы': "Zamburug'ga surtma",
  'Соскоб на демодекоз': 'Demodekozga surtma',
  'Соскоб на чесотки': "Qichishchaga surtma",
  'С-реактивный белок GPR': 'C-reaktiv belok (GPR)',
  'Тестостерон': 'Testosteron',
  'Тиреотропный гармон (TTG)': 'TTG (tirotrop gormoni)',
  'Трийодтрионин свободный (FT3)': 'Erkin trijodtironin (FT3)',
  'Триоксин свободный (FT4)': 'Erkin tiroksin (FT4)',
  'Ферритин': 'Ferritin',
  'ФСГ': 'FSG',
  'ХГЧ': 'xGCH',
  'Холестерин Общ.': 'Umumiy xolesterin',
  'Биопсия': 'Biopsiya',
  'Лактатдегидрогеназа (ЛДГ)': 'Laktatdegidrogenaza (LDG)',
  'ТТГ общий': 'Umumiy TTG',
  'Трийодтиронин Т3 общий': 'Umumiy T3 (trijodtironin)',
  'Тироксин общий Т4': 'Umumiy T4 (tiroksin)',
  'Антитела к тиреоглобулину (АТ-ТГ)': 'Tireoglobulinga antitanalar (AT-TG)',
  'Антитела к териопироксидазе (АТ-ТПО)': 'Tireoperoksidazaga antitanalar (AT-TPO)',
  'Бак иследование носа': 'Burun bakteriologik tekshiruvi',
  'Бак исследование со слизистой оболочки из зева': 'Bakteriologik tekshiruv: tomoq shilliq qavatidan',
  'Трийодтиронин Т3 свободный': 'Erkin T3 (trijodtironin)',
  'Тироксин свободный Т4': 'Erkin T4 (tiroksin)',
  'Кал на лямблии и другие простейшие': 'Kal tahlili: lambliyalar va boshqa oddiy bir hujayralilar',
  'Антитела к растворимому антигену печенипеченочно-панкреатическому антигену (Anti SLA LP IgG)':
    "Eriydigan jigar-o'pka pankreas antigeniga antitanalar (Anti-SLA/LP IgG)",
  'Антинуклеарные антитела (АНА)': 'Antinuklear antitanalar (ANA)',
  'Гистологическое исследование': 'Gistologik tekshiruv',
  'Анализ кала на простейшие, в т.ч. лямблии': 'Kal tahlili: oddiy bir hujayralilar (jumladan lambliyalar)',
  'Общий анализ крови (24 показателей)': "Qonning umumiy tahlili (24 ko'rsatkich)",
  'Общий анализ крови без лейкоформулы': 'Qonning umumiy tahlili (leykotsit formulasisiz)',
  'Общий анализ крови + тромбоциты': 'Qon + trombotsitlar umumiy tahlili',
  'Скорость оседания эритроцитов (СОЭ)': 'Eritrotsitlar cho\'kish tezligi (SOE)',
  'Мазок на эозинофилы': 'Eozinofillar uchun surtma',
  'Концентрация гемоглобина': 'Gemoglobin konsentratsiyasi',
  'LE-клетки': 'LE-hujayralar',
  'Антитела к Rh-фактору': 'Rh-faktorga antitanalar',
  'Группа крови – Резус фактор': 'Qon guruhi — Rezus faktor',
  '3х-стаканная проба мочи': 'Siydikning 3 stakanga proba tahlili',
  'Моча по Нечипоренко': 'Siydik bo\'yicha Nechiporenko',
  'Моча по Зимницкому': 'Siydik bo\'yicha Zimnitskiy',
  'Моча на желчные пигменты': "Siydikdagi o't pigmentlari",
  'Моча на ацетон': 'Siydikdagi atseton',
  'Микроальбумин в моче': 'Siydikdagi mikroalbumin',
  'Белок в моче': 'Siydikdagi belok',
  'ХГ в моче': 'Siydikdagi xGCH',
  'Глюкоза в моче': 'Siydikdagi glukoza',
  'Цитология осадка мочи': 'Siydik cho\'kindisi tsitologiyasi',
  'Общий мазок на флору': 'Umumiy surtma (flora)',
  'Цитология мазка (PAP-тест)': 'Surtma tsitologiyasi (PAP-test)',
  'Мазок на ВПЧ (HPV)': 'VPCh (HPV) uchun surtma',
  'Цитологическое исслед. на атипические клетки': 'Sitologik tekshiruv: atipik hujayralar',
  'Спермограмма': 'Spermogramma',
  'Сок простаты': 'Prostata soki',
  'Нативный мазок на трихомониаз': 'Trixomoniyaz uchun native surtma',
  'Женский мазок на лептотрихоз': 'Ayollar surtmasi: leptotriks',
  'Общий анализ мокроты': 'Balg\'amning umumiy tahlili',
  'Назальный секрет (Эозинофилы)': 'Burun sekreti (eozinofillar)',
  'Демодекоз': 'Demodekoz (surtma)',
  'Анализ на грибок (с гладкой кожи и': "Zamburug' tahlili (silliq teri va sochli bosh qismidan)",
  'Волосистой части головы)': "Zamburug' tahlili (sochli bosh qismi)",
  'Чесоточный клещ': 'Qichishcha kanasi',
  'Лейшманиоз': 'Leyshmanioz',
  'Тест на совместимость (Курцрока-Миллера)': 'Moslik testi (Kurtsrok — Miller)',
  'Проба Шуварского – Симса Гунера': 'Shuvarskiy — Sims Gunera probasi',
  'Проба на антиспермальные антитела': 'Antisperm antitanalar testi',
  'MAR - тест': 'MAR-test',
  'Анализ кала на яйца гельминтов': 'Kal tahlili: gelmint tuxumlari',
  'Копрограмма (общий анализ кала)': 'Koprogramma (kalning umumiy tahlili)',
  'Анализ кала на скрытую кровь': 'Kal tahlili: yashirin qon',
  'Соскоб на энтеробиоз (острицы)': 'Enterobiozga surtma (kaltakesaklar)',
  'Время Свертываемости крови': 'Qon ivish vaqti',
  'Длительность кровотечения': 'Qon ketish davomiyligi',
  'Протромбиновое время (PT)': 'Protrombin vaqti (PT)',
  'Тромбо динамика': 'Trombo-dinamika',
  'Фибриноген': 'Fibrinogen',
  'Коалиновое время': 'Kaolin vaqti',
  'АЧТВ (активное частичное тромбопластиновое время)': 'aPTT (faol qisman tromboplastin vaqti)',
  'МНО': 'MNO',
  'ПТИ': 'PTI',
  'Тромбиновое время (TT)': 'Trombin vaqti (TT)',
  'Д - димер (D - dimer)': 'D-dimer',
  'Антитромбин III': 'Antitrombin III',
  'Волчаночный антикоагулянт - подтверждающий (LA-2)': 'SLE antikoagulyanti — tasdiqlovchi test (LA-2)',
  'Волчаночный антикоагулянт - скрининг (LA-1)': 'SLE antikoagulyanti — skrining (LA-1)',
  'HAV IgM (Гепатит А)': 'HAV IgM (A gepatiti)',
  'HBsAg (Гепатит В)': 'HBsAg (B gepatiti)',
  'HCV (Гепатит С)': 'HCV (C gepatiti)',
  'RW - (Экспрес PRP - тест)': 'RW (ekspress PRP-test)',
  'Helicobacter pylory (кровь, кал)': 'Helicobacter pylori (qon, kal)',
  'Дыхательно- уреазный тест на определение Helicobacter pylory':
    'Helicobacter pylori aniqlash uchun nafas ureaza testi',
  'Тропонин I': 'Troponin I',
  'Бруцеллёз (Rose Bengal)': 'Brutsellez (Rose Bengal)',
  'СПИД (ВИЧ) Экспресс': 'OITS (VICh) ekspress-test',
  'СПИД (ВИЧ) Экспресс (иностранцам)': 'OITS (VICh) ekspress-test (chet elliklar uchun)',
  'SARS-CoV-2 IgM/IgG': 'SARS-CoV-2 IgM/IgG',
  'SARS-CoV-2- Antigen': 'SARS-CoV-2 antigen',
  'Глюкозо - толерантный тест': 'Glukoza tolerantlik testi',
  'АКЦИЯ Глюкоза крови': 'AKSIYA: qondagi glukoza',
  'Глюкоза мочи': 'Siydikdagi glukoza',
  'Глюкоза через 2 часа после еды': 'Ovqatdan 2 soat keyin glukoza',
  'Гликолизированный гемоглобин': 'Glikozillangan gemoglobin (HbA1c)',
  'Индекс НОМА (инсулин + глюкоза натощак)': 'NOMA indeksi (insulin + och qoringa glukoza)',
  'Фруктозамин': 'Fruktozamin',
  'Общий билирубин': 'Umumiy bilirubin',
  'Прямой билирубин': "To'g'ridan-to'g'ri bilirubin",
  'Трансаминаза-АЛТ': 'Transaminaza — ALT',
  'Трансаминаза-АСТ': 'Transaminaza — AST',
  'Тимоловая проба': 'Timol probasi',
  'ГГТ': 'GGT',
  'Желчные кислоты': "O't kislotalari",
  'Общий холестерин': 'Umumiy xolesterin',
  'HDL-холестерин (Высокой плотности)': 'HDL-xolesterin (yuqori zichlik)',
  'LDL-холестерин (Низкой плотности)': 'LDL-xolesterin (past zichlik)',
  'Триглицериды': 'Triglitseridlar',
  'Аполипопротеин А1': 'Apolipoprotein A1',
  'Аполипопротеин В': 'Apolipoprotein B',
  'Железо': 'Temir',
  'Общая железосвязывающая способность (ОЖС)': 'Umumiy temir bog\'lovchi qobiliyat (OJS)',
  'Трансферрин': 'Transferrin',
  'Эритропоэтин': 'Eritropoetin',
  'Альфа-амилаза (диастаза) крови': 'Alfa-amilaza (diastaza) — qon',
  'Альфа-амилаза (диастаза) мочи': 'Alfa-amilaza (diastaza) — siydik',
  'Липаза (Lipase)': 'Lipaza',
  'Щелочная фосфатаза (ALP)': 'Ishqoriy fosfataza (ALP)',
  'Кислая фосфатаза (ACP)': 'Kislo fosfataza (ACP)',
  'Лактодегидрогеназа (LDG)': 'Laktatdegidrogenaza (LDG)',
  'Холинэстераза': 'Xolinesteraza',
  'Гамма-глютамилтрансфераза (GGT)': 'Gamma-glyutamiltransferaza (GGT)',
  'Креатининкиназа (КФК)': 'Kreatinkinaza (KFK)',
  'Креатининкиназа - МВ (КФК - МВ)': 'Kreatinkinaza-MV (KFK-MV)',
  'Цистатин С': 'Tsistatin C',
  'Глюкоматдекарбоксилаза (Анти-GAD)': 'Glyukomatdekarboksilaza (Anti-GAD)',
  'Эластаза (Elastasa)': 'Elastaza',
  'Проба Реберга': 'Reberg probasi',
  'Мочевая кислота в крови': 'Qondagi mochevina kislotasi',
  'Мочевая кислота в суточной моче': 'Sutkalik siydikdagi mochevina kislotasi',
  'Калий (K)': 'Kaliy (K)',
  'Натрий (Na)': 'Natriy (Na)',
  'Хлориды (Cl)': 'Xloridlar (Cl)',
  'Магний (Mg)': 'Magniy (Mg)',
  'Кальций в крови (Ca)': 'Qondagi kalsiy (Ca)',
  'Кальций в моче (Ca)': 'Siydikdagi kalsiy (Ca)',
  'Фосфор (P)': 'Fosfor (P)',
  'Железо (Fe)': 'Temir (Fe)',
  'Комплекс электролитов (группа)': 'Elektrolitlar kompleksi (guruh)',
  'Цинк': 'Rux',
  'Медь': 'Mis',
  'Витамин D': 'D-vitamin',
  'Витамин B12': 'B12-vitamin',
  'Фолиевая кислота': 'Foliy kislota',
  'Гомоцистеин': 'Gomotsistein',
  'С-Реактивный белок': 'C-reaktiv belok',
  'Антистрептолизин': 'Antistreptolizin-O',
  'Антитела к циклическому цитруллин': 'Tsiklik tsitrullinga antitanalar',
  'Миоглобин': 'Mioglobin',
  'Прокальцитонин': 'Prokalsitonin',
  'С - реактивный белок': 'C-reaktiv belok',
  'Остеокальцин': 'Osteokalsin',
  'Мозговой натрийуретический пептид (NT pro BNP)': 'Miya natriyuretik peptid (NT pro BNP)',
  'IgA': 'IgA',
  'IgM': 'IgM',
  'IgG': 'IgG',
  'ТТГ': 'TTG',
  'Т3': 'T3',
  'Т3 свободный': 'Erkin T3',
  'Т4': 'T4',
  'Т4 свободный': 'Erkin T4',
  'Антитела к ТГ': 'TG ga antitanalar',
  'Антитела к ТПО': 'TPO ga antitanalar',
  'Тиреоглобулин': 'Tireoglobulin',
  'Прогестерон (Progesterone)': 'Progesteron (Progesterone)',
  'Эстрадиол (Estradiol)': 'Estradiol',
  'Эстриол (Free Estriol)': 'Estriol (Free Estriol)',
  'Пролактин (Prolactin)': 'Prolaktin (Prolactin)',
  'Тестостерон (Testosterone)': 'Testosteron (Testosterone)',
  'Свободный тестостерон (Free Testosterone)': 'Erkin testosteron (Free Testosterone)',
  'Фоликулостимулирующий гормон (FSH)': 'Follikulostimulyatsiya gormoni (FSH)',
  'Лютеинизирующий гормон (LH)': 'Lyuteinizatsiya gormoni (LH)',
  'Дегидроэпиандростерон-сульфат (DHEAS)': 'Degidroepiandrosteron-sulfat (DHEAS)',
  '17- ОН прогестерон': '17-OH progesteron',
  'Антимюллеров гормон (АМГ)': 'Antimyuller gormoni (AMG)',
  'Глобулин, связывающий половые гормоны (SHBG)': "Jinsiy gormonlarni bog'lovchi globulin (SHBG)",
  'Ингибин В': 'Ingibin B',
  'Кортизол (утро)': 'Kortizol (ertalab)',
  'Кортизол (вечер)': 'Kortizol (kechqurun)',
  'Соматотропный гормон (СТГ)': 'Somatotrop gormon (STG)',
  'Инсулиноподобный фактор роста (ИФР)': "Insulinga o'xshash o'sish faktori (IFR)",
  'Протеин-3, связывающий инсулиноподобный': "Insulinga o'xshash faktorni bog'lovchi protein-3",
  'Фактор роста (IGFBP-3)': "O'sish faktori (IGFBP-3)",
  'Адренокортикотропный гормон (АКТГ)': 'Adrenokortikotrop gormon (AKTG)',
  'Адреналин/Норадреналин': 'Adrenalin/Noradrenalin',
  'Паратгормон (PTH)': 'Paratgormon (PTH)',
  'ХГЧ – ранняя диагностика беременности': 'xGCH — erta homiladorlikni aniqlash',
  'ХГЧ – точное разведение': 'xGCH — aniq suyultirish',
  'AFP - Алфа-фетопротеин': 'AFP — alfa-fetoprotein',
  'Эстриол свободный (Free estriol)': 'Erkin estriol (Free estriol)',
  'Свобод. Хорионич. гонадотропин (Free-B-HCG)': 'Erkin xorionik gonadotropin (Free-B-HCG)',
  'PAPP - A (белок А плазмы ассоциированный': 'PAPP-A (homiladorlik bilan bog\'liq plazma A proteini',
  'С беременностью)': 'PAPP-A (homiladorlik bilan bog\'liq plazma A proteini)',
  'АФП+ХГЧ+Эстриол': 'AFP+xGCH+Estriol',
  'Раковый эмбриональный антиген (CEA)': 'Saraton embrional antigeni (CEA)',
  'Углеводный антиген СА-15-3 (молочная железа)': 'Uglevod antigen SA-15-3 (sut bezi)',
  'Углеводный антиген СА-19-9 (поджелудочная': 'Uglevod antigen SA-19-9 (oshqozon osti bezi + JKT)',
  'Железа + ЖКТ)': 'Uglevod antigen SA-19-9 (oshqozon osti bezi + JKT)',
  'Углеводный антиген СА-72-4 (желудок)': 'Uglevod antigen SA-72-4 (oshqozon)',
  'Углеводный антиген СА-125 (яичники)': 'Uglevod antigen SA-125 (tuxumdonlar)',
  'CYFRA 21-1': 'CYFRA 21-1',
  'НЕ-4 (яичники)': 'NE-4 (tuxumdonlar)',
  'Нейрон специфическая енолаза (NSE - лёгкие)': "Neyron-spetsifik enolaza (NSE — o'pka)",
  'Альфа-фетопротеин (AFP - печень)': 'Alfa-fetoprotein (AFP — jigar)',
  'Хорионический гонадотропин (ХГЧ - яички, пуз. занос)': 'Xorionik gonadotropin (xGCH — moya, qorin ko\'chirish)',
  'Простатспецифический антиген общий (PSA)': 'Umumiy PSA (prostata-spetsifik antigen)',
  'Простатспецифический антиген свобод. (Free-PSА)': 'Erkin PSA (Free-PSA)',
  'Индекс ROMA (HE-4+CA125)': 'ROMA indeksi (HE-4+CA125)',
  'Антиген плоскоклеточной карциномы (SCC)': 'Tekis hujayrali kartsinoma antigeni (SCC)',
  'Тиреоглобулин (щитовидная железа)': 'Tireoglobulin (qalqonsimon bez)',
  'S 100 (маркер потенциального повреждения': 'S-100 (potentsial zararlanish markeri)',
  'Микоплазма Mycoplasma genitalium': 'Mikoplazma Mycoplasma genitalium',
  'Уреаплазма Ureaplasma urealiticum': 'Ureaplazma Ureaplasma urealiticum',
  'Уреаплазма Ureaplasma parvum': 'Ureaplazma Ureaplasma parvum',
  'Гонококк Neisseria gonorrhoeae': 'Gonokokk Neisseria gonorrhoeae',
  'Трихомонада Trichomonas vaginalis': 'Trixomonada Trichomonas vaginalis',
  'Гарднерелла Gardnerella vaginalis': 'Gardnerella Gardnerella vaginalis',
  'Цитомегаловирус Cytomegalovirus качество': 'Sitomegalovirus Cytomegalovirus (sifat)',
  'Цитомегаловирус Cytomegalovirus количество': 'Sitomegalovirus Cytomegalovirus (miqdor)',
  'Вирус простого герпеса Herpes Simplex Virus? качество': 'Oddiy herpes virusi HSV (sifat)',
  'Вирус простого герпеса Herpes Simplex Virus 8 количество': 'Oddiy herpes virusi HSV-8 (miqdor)',
  'С-пептид': 'C-peptid',
  'Общий IgE': 'Umumiy IgE',
  'Аллергопанели (смешанная)': 'Allergopanel (aralash)',
  'Аллергопанели (ингаляционна)': 'Allergopanel (ingalyatsion)',
  'Аллергопанели (пищевая)': 'Allergopanel (oziq-ovqat)',
  'Антинуклеарные антитела (ANA)': 'Antinuklear antitanalar (ANA)',
  'Антиспермальные антитела (АСА)': 'Antisperm antitanalar (ASA)',
  'Антитела к фосфолипидам (AFS) IgM IgG': 'Fosfolipidga antitanalar (AFS) IgM IgG',
  'Антитела к митохондриям (АМА)': 'Mitoxondriyaga antitanalar (AMA)',
  'Антитела к миелопероксидазе (Анти-МРО)': 'Mieloperoksidazaga antitanalar (Anti-MPO)',
  'Антитела к модифицированному цитруллинированому виментину (A-MCV)':
    'Modifikatsiyalangan tsitrullinlangan vimentinga antitanalar (A-MCV)',
  'Целиакия (трансглутаминаза IgA) количественный': 'Tseliakiya (transglutaminaza IgA) miqdoriy',
  'Целиакия (антитела к глиадину IgA) количественный': 'Tseliakiya (gliadinga antitanalar IgA) miqdoriy',
  'Целиакия (антитела к глиадину IgG) количественный': 'Tseliakiya (gliadinga antitanalar IgG) miqdoriy',
  'IgG к одноцепочечнойДНК, IgG к двухцепочечнойДНК': 'IgG bir zanjirli DNK va ikki zanjirli DNK ga',
  'Anti - histone – Определение антител к гистонам': 'Anti-histone — gistonlarga antitanalar aniqlash',
  'Anti - PR3 – Определение антител к протеиназе 3': 'Anti-PR3 — proteinaza 3 ga antitanalar aniqlash',
  'Аутоиммунная панель-10 антигенов': 'Autoimmun panel — 10 antigen',
  '(AMA M2, SP100, gp210, LKM1, LC1, CENP-B, GBM, PR3, MPO, SLA/LP) NEW':
    'Autoimmun panel (AMA M2, SP100, gp210, LKM1, LC1, CENP-B, GBM, PR3, MPO, SLA/LP)',
  'Антитела к Saccharomyces cerevisiae (ASCA) Ig G': 'Saccharomyces cerevisiae (ASCA) IgG ga antitanalar',
  'Антинейтрофильные цитоплазматические': 'Antineytrafil sitoplazmatik antitanalar (ANCA)',
  'Антитела (ANCA)': 'Antineytrafil sitoplazmatik antitanalar (ANCA)',
  'Интерлейкин 2 (ИЛ 2)': 'Interleykin 2 (IL-2)',
  'Интерлейкин 6 (ИЛ 6)': 'Interleykin 6 (IL-6)',
  'Интерлейкин 10 (ИЛ 10)': 'Interleykin 10 (IL-10)',
  'Интерлейкин 4 (ИЛ 4)': 'Interleykin 4 (IL-4)',
  'Интерлейкин 8 (ИЛ 8)': 'Interleykin 8 (IL-8)',
  'Компонент комплемента С3 (С3-Complement Factor)': 'Komplement komponenti C3',
  'Компонент комплемента С4 (С4-Complement Factor)': 'Komplement komponenti C4',
  'Антитела к лямблиям суммарные': 'Lambliyaga umumiy antitanalar',
  'Антитела к лямблиям IgG': 'Lambliyaga IgG antitanalar',
  'Антитела к аскаридам IgG': 'Askariidga IgG antitanalar',
  'Антитела к эхинококку IgG': 'Exinokokkka IgG antitanalar',
  'Гельминты (токсокароз, описторхоз, трихенеллёз,': 'Gelmintlar (toksokaroz, opistorxoz, trixineloz,',
  'Эхинококкоз)': 'exinokokkoz)',
  'HAV (Гепатит A) IgM IgG по': 'HAV (A gepatiti) IgM/IgG antitanalari',
  'Anti Hbs (Антитела к поверхностному антигену гепатита B)': 'Anti-HBs (B gepatiti yuzaki antigeniga antitanalar)',
  'Anti HBc (Антитела к ядерному антигену гепатита B) IgM, IgG':
    'Anti-HBc (B gepatiti yadro antigeniga antitanalar) IgM, IgG',
  'HBeAg (Антиген оболочки гепатита B)': 'HBeAg (B gepatiti qobiq antigeni)',
  'Anti Hbe (Антитела к антигену оболочки гепатита B)': 'Anti-HBe (B gepatiti qobiq antigeniga antitanalar)',
  'Anti HCV (Гепатит C)': 'Anti-HCV (C gepatiti)',
  'Anti HDV (Гепатит D)': 'Anti-HDV (D gepatiti)',
  'HEV IgM (Гепатит E)': 'HEV IgM (E gepatiti)',
  'A.R.I. WELL D-ONE': 'A.R.I. WELL D-ONE',
  'OYRON WELL D-ONE': 'OYRON WELL D-ONE',
  'UROGEN WELL D-ONE': 'UROGEN WELL D-ONE',
  'Носа': 'Burun surtmasi',
  'Со слизистой оболочки зева': 'Tomoq shilliq qavatidan surtma',
  'Конъюнктивы': 'Kon\'yunktiva surtmasi',
  'Уха': 'Quloq surtmasi',
  'Кровь на стерильность': 'Qon sterilligi tekshiruvi',
  'С участка поражения': 'Zararlangan hududdan surtma',
  'Мокроты': 'Balg\'am',
  'Мочи': 'Siydik',
  'Urethra': 'Uretra',
  'Vagina': 'Vagina',
  'Cervical': 'Serviks',
  'С 3х точек (urethra.vagina.cervical)': '3 nuqtadan surtma (uretra, vagina, serviks)',
  'Спермы': 'Sperma',
  'Сока простаты.': 'Prostata soki',
  'Грудное молоко на стерильность': 'Ko\'krak suti sterilligi tekshiruvi',
  'Плевральная жидкость': 'Plevra suyuqligi',
  'Спинномозговая жидкость': 'Orqa miya suyuqligi',
  'Кал (дизбактериоз)': 'Kal (disbakterioz)',
  'Кишечная группа (Дизентерия, сальмонелез)': 'Ichak guruhi (dizenteriya, salmonelez)',
  'Кишечная группа (Дизентерия, сальмонелез, стафилококк)':
    'Ichak guruhi (dizenteriya, salmonelez, stafilokokk)',
  'Антитела к токсоплазме IgM': 'Toksoplazmaga IgM antitanalar',
  'Антитела к токсоплазме IgG': 'Toksoplazmaga IgG antitanalar',
  'Антитела к ЦМВ IgM': 'TsMV ga IgM antitanalar',
  'Антитела к ЦМВ IgG': 'TsMV ga IgG antitanalar',
  'Антитела к вирусу герпеса I типа IgM': 'Herpes virusi I tipiga IgM antitanalar',
  'Антитела к вирусу герпеса I типа IgG': 'Herpes virusi I tipiga IgG antitanalar',
  'Антитела к вирусу герпеса II типа IgM': 'Herpes virusi II tipiga IgM antitanalar',
  'Антитела к вирусу герпеса II типа IgG': 'Herpes virusi II tipiga IgG antitanalar',
  'Антитела к вирусу краснухи IgM': 'Qizamiq virusiga IgM antitanalar',
  'Антитела к вирусу краснухи IgG': 'Qizamiq virusiga IgG antitanalar',
  'Антитела к хламидиям IgM': 'Xlamidiyaga IgM antitanalar',
  'Антитела к хламидиям IgG': 'Xlamidiyaga IgG antitanalar',
  'Антитела к микоплазме M.hominis Ig.A Ig.M Ig.G': 'Mikoplazma M.hominis ga IgA, IgM, IgG antitanalar',
  'Антитела к уреаплазме U.urealiticum Ig.A Ig.M Ig.G': 'Ureaplazma U.urealiticum ga IgA, IgM, IgG antitanalar',
  'Антитела к гарднерелле IgG': 'Gardnerellaga IgG antitanalar',
  'Антитела к трихомонаде IgG': 'Trixomonadaga IgG antitanalar',
  'Антитела к кандиде по IgM IgG': 'Kandidaga IgM va IgG antitanalar',
  'Антитела к хламидиям пневм. по IgM IgG': 'O\'pka xlamidiyasiga IgM va IgG antitanalar',
  'Антитела к микоплазме пнев. по IgM IgG': 'O\'pka mikoplazmasiga IgM va IgG antitanalar',
  'Helicobacter pylori суммарные': 'Helicobacter pylori umumiy antitanalar',
  'Helicobacter pylori IgM IgG': 'Helicobacter pylori IgM va IgG',
  'Вирус Эпштейн-Барра VCA IgG': 'Epstein-Barr virusi VCA IgG',
  'Вирус Эпштейн-Барра VCA IgM': 'Epstein-Barr virusi VCA IgM',
  'Вирус Эпштейн-Барра IgG к раннему антигену ЕА': 'Epstein-Barr virusi erta EA antigeniga IgG',
  'Вирус Эпштейн-Барра IgG к ядерному антигену NA': 'Epstein-Barr virusi yadro NA antigeniga IgG',
  'VZV (Вирус Зостер) IgM': 'VZV (Virus Zoster) IgM',
  'Бруцеллёз IgM': 'Brutsellez IgM',
  'Корь IgМ': 'Qizilcha IgM',
  'Корь IgG': 'Qizilcha IgG',
  'Коклюш IgМ': 'Koklyush IgM',
  'Коклюш IgG': 'Koklyush IgG',
  'СПИД (ВИЧ) ИФА ОИТС (Иностранцам)': 'OITS (VICh) IFA testi (chet elliklar uchun)',
  'СПИД (ВИЧ) ИФА ОИТС': 'OITS (VICh) IFA testi',
  'Анти-SARS-CoV-2 IgM': 'Anti-SARS-CoV-2 IgM',
  'Анти-SARS-CoV-2 IgG': 'Anti-SARS-CoV-2 IgG',
  'Anti – RBD антитела к коронавирусу SARS – CoV 2': 'Anti-RBD SARS-CoV-2 koronavirusiga antitanalar',
  'Туберкулёз – Антитела': 'Sil kasalligi — antitanalar',
  'Антитела к токсоплазме': 'Toksoplazmaga antitanalar',
  'Антитела к ЦМВ': 'TsMV ga antitanalar',
  'Антитела к ВПГ': 'VPG ga antitanalar',
  'Антитела к Краснухе': 'Qizamiqqa antitanalar',
  'Гепатит В (качественный)': 'B gepatiti (sifatli)',
  'Гепатит В (количественный)': 'B gepatiti (miqdoriy)',
  'Гепатит С (качественный)': 'C gepatiti (sifatli)',
  'Гепатит С (количественный)': 'C gepatiti (miqdoriy)',
  'Гепатит С (Генотипирование)': 'C gepatiti (genotiplashtirish)',
  'Гепатит D (качественный)': 'D gepatiti (sifatli)',
  'Гепатит D (количественный)': 'D gepatiti (miqdoriy)',
  'Вирус Эпштейна-Барра (EBV) кровь качественный': 'Epstein-Barr virusi (EBV) qon — sifatli',
  'Вирус Эпштейна-Барра (EBV) кровь количественный': 'Epstein-Barr virusi (EBV) qon — miqdoriy',
  'Вирус Эпштейна-Барра (EBV) слюна качественный': 'Epstein-Barr virusi (EBV) tupruk — sifatli',
  'Вирус Эпштейна-Барра (EBV) слюна количественный': 'Epstein-Barr virusi (EBV) tupruk — miqdoriy',
  'VZV (Вирус Зостер)': 'VZV (Virus Zoster)',
  'Туберкулез (Mycobacterium tuberculosis/bovis)': 'Sil kasalligi (Mycobacterium tuberculosis/bovis)',
  'Сальмонеллёз': 'Salmonellyoz',
  'Хламидия пневмония': 'Xlamidiya pnevmoniyasi',
  'Бруцеллез РТ-ПЦР': 'Brutsellez RT-PTSR',
  'Helicobacter pylori слюна, Желудочный сок по': 'Helicobacter pylori (tupruk, oshqozon soki)',
  'SARS-CoV-2 (Covid-19)': 'SARS-CoV-2 (COVID-19)',
  'Хламидия Chlamidia trachomatis': 'Xlamidiya Chlamydia trachomatis',
  'Антитела к лямблиям IgM': 'Lambliyaga IgM antitanalar',
  'Анализ на грибок (ногтей) руки': "Qo'l tirnoqlaridan zamburug' tahlili",
  'Антитела к рецепторам ТТГ (анти-рТТГ)': 'TTG retseptorlariga antitanalar (anti-rTTG)',
  'Панель В27 HLA': 'HLA B27 panel',
  'HLA II класс (DRB 1, DQA 1, DQB 1)': 'HLA II klass (DRB1, DQA1, DQB1)',
  'HLA I класс (HLA – A, HLA – B, HLA – DR)': 'HLA I klass (HLA-A, HLA-B, HLA-DR)',
  'Скрингенетика метаболизма фолатов': 'Folat metabolizmi skrining-genetikasi',
  '(MTHFR, MTR, MTRR)': 'Folat metabolizmi (MTHFR, MTR, MTRR)',
  'ОнкоГенетика BRCA (риск развития рака молочной': 'Onko-genetika BRCA (sut bezi, tuxumdon va qalin ichak saraton xavfi)',
  'Железы, рака яичника, рака толстого кишечника)':
    'Onko-genetika BRCA (sut bezi, tuxumdon va qalin ichak saraton xavfi)',
  'Скрингенетика гипертонической болезни': 'Gipertoniya skrining-genetikasi',
  '(ADD1, AGT, AGTR, GNB3, NOS3)': 'Gipertoniya (ADD1, AGT, AGTR, GNB3, NOS3)',
  'Скрингенетика азооспермии-мужское бесплодие.': 'Azoospermiya skrining-genetikasi — erkak bepushtligi',
  'Делеции локуса AZF': 'AZF lokus deletsiyasi',
  'Скрингенетика муковисцыдоза.': 'Mukovistsidoz skrining-genetikasi',
  'Мутации гена CIFTR': 'CFTR gen mutatsiyasi',
  'Генетика Синдрома Жельбера': 'Jelber sindromi genetikasi',
  'Определение Полиморфизма гена вит Д': 'D vitamini geni polimorfizmini aniqlash',
  'Тест на отцовство/материнство, 25 маркеров': 'Otalik/onalik testi (25 marker)',
  'Кариотип анализ экспертного уровня': 'Kariotip tahlili (ekspert darajasi)',
  'Неинвазивное определение пола плода. Стандартный тест (точность 99 %)':
    'Homila jinsini invaziv bo\'lmagan aniqlash — standart test (99% aniqlik)',
  'Неинвазивное определение пола плода. Определние риска развития аномалий хромосомного набора плода. Экспертный тест. (точность 99.9 %)':
    'Homila xromosoma anomaliyalari xavfini invaziv bo\'lmagan aniqlash — ekspert test (99.9% aniqlik)',
  'Иммуногенетика IL 28- B в прогнозе противовирусной терапии при ВГС':
    'Immunogenetika IL28B — VGS da antiviral terapiya prognozi',
  'Выделение ДНК из нестандартного образца': 'Nostandart namunadan DNK ajratish',
  'НИПТ Panorama (Natera, США), « Базовая панель 22 q»': 'NIPT Panorama (Natera, AQSh) — asosiy panel 22q',
  'НИПТ Panorama (Natera, США), « Расширенная панель »': 'NIPT Panorama (Natera, AQSh) — kengaytirilgan panel',
  'НИПТ Синдром Дауна, Эдварса, Патау «Базовая панель»': 'NIPT Daun, Edvards, Patau sindromlari — asosiy panel',
  'НИПТ Синдром Дауна, Эдварса, Патау, Шепешевского –Тернера, Клайнфельтера « Стандартная панель»':
    'NIPT Daun, Edvards, Patau, Shepeshovskiy-Terner, Klaynfelter — standart panel',
  'Кардио генетика Тромбофилия': 'Kardio-genetika — trombofiliya',
  'Такролимус': 'Takrolimus',
  'TORCH Ig M ИХЛА (токсоплазма, ЦМВ, хламадия, микоплазма, уреоплазма, рубелла., герпес I, ll тип)':
    'TORCH IgM IXLA (toksoplazma, TsMV, xlamidiya, mikoplazma, ureaplazma, qizamiq, herpes I va II tip)',
  'TORCH Ig G ИХЛА (токсоплазма, ЦМВ, хламадия, микоплазма, уреоплазма, рубелла., герпес I, ll тип)':
    'TORCH IgG IXLA (toksoplazma, TsMV, xlamidiya, mikoplazma, ureaplazma, qizamiq, herpes I va II tip)',
  'TORCH ПЦР': 'TORCH RT-PTSR',
  'Гистологическое иследование': 'Gistologik tekshiruv',
  'СА-242 раковый антиген для диагностики рака поджелудочной железы толстог7о кишечника прямой кишки':
    "SA-242 — oshqozon osti bezi, qalin va to'g'ri ichak saratonini aniqlash uchun onkogen antigen",
  'СА-50 маркер гастроинестинальных новообразования в первую очередь желудочной железы':
    'SA-50 — gastrointestinal o\'smalar markeri (asosan oshqozon)',
  'HER-2 рецептр один из наиболее значимых молекулярных маркеров при раке молочной зелёз':
    'HER-2 retseptor — sut bezi saratonidagi muhim molekulyar marker',
  'PRO-GRP Прогастрин высвобождающий белок высокочувствительных маркер мелкоклеточного рака лёгких':
    "PRO-GRP — mayda hujayrali o'pka saratonining yuqori sezgir markeri",
  'Кальцитонинг (медулярный рак щитовидной железы)': 'Kalsitonin (qalqonsimon bez medullyar saraton)',
  'Вирус герпеса человека 6 тип, 8 тип качество по': 'Inson herpes virusi 6 va 8 tipi (sifat)',
  'Вирус герпеса человека 6 тип, 8 тип количество по': 'Inson herpes virusi 6 va 8 tipi (miqdor)',
  'ВПЧ 16 (Papilomavirus 16)': 'VPCh 16 (Papillomavirus 16)',
  'ВПЧ 18 (Papilomavirus 18)': 'VPCh 18 (Papillomavirus 18)',
  'ВПЧ 6, 11': 'VPCh 6, 11',
  'ВПЧ 16, 31, 33, 35, 52, 6, 11, 18, 39, 45, 59, 58, 51, 56, 68 (HPV квант -15':
    'VPCh 16, 31, 33, 35, 52, 6, 11, 18, 39, 45, 59, 58, 51, 56, 68 (HPV kvant-15)',
  'ВПЧ 31, 35, 16, 53, 33, 68, 45, 82, 51, 6, 44, 11, 18, 39, 58, 66, 26, 53, 59, 56, 73 (HPV квант-21)':
    'VPCh 31, 35, 16, 53, 33, 68, 45, 82, 51, 6, 44, 11, 18, 39, 58, 66, 26, 53, 59, 56, 73 (HPV kvant-21)',
  'Комплекс: (Cand.albicans, Cand.glabrata, Cand.krusei) (мазок, моча, ротоглотка)':
    "Kompleks: Candida albicans, C. glabrata, C. krusei (surtma, siydik, og'iz-boqish)",
  'Скрин Микоз РТ-ПЦР(выявление и типированиевозбудителей грибковых инфекций)':
    "Mikoz skriningi RT-PTSR (zamburug' infeksiyalari qo'zg'atolchilarini aniqlash va tipizatsiya)",
  '12-ОРЗ-панель РТ-ПЦР (острые респираторные заболевания)': '12-ORZ panel RT-PTSR (o\'tkir respirator kasalliklar)',
  'АБ-ГенРезиста РТ-ПЦР (выявление генов резистентности к антибиотикам)':
    'AB-GenRezista RT-PTSR (antibiotiklarga chidamlilik genlarini aniqlash)',
  'Фемофлор 16': 'Femoflor 16',
  'Фемофлор скрин': 'Femoflor skrining',
  'Андрофлор': 'Androflor',
  'Хламидия': 'Xlamidiya',
  'Скорость оседания эритроцитов': 'Eritrotsitlar cho\'kish tezligi (SOE)',
  'Гистологическое исследования соскоба матки': 'Bachadon surtmasi gistologik tekshiruvi',
  'ПАП тест': 'PAP-test',
  'Ренин': 'Renin',
};

function translateLab(ru) {
  const trimmed = ru.trim();
  if (EXACT[trimmed]) return EXACT[trimmed];

  // Pattern: Антитела к X
  let m = trimmed.match(/^Антитела к (.+)$/i);
  if (m) {
    const target = m[1].trim();
    if (/^циклическому цитруллин/i.test(target)) return 'Tsiklik tsitrullinga antitanalar';
    if (/^токсоплазме$/i.test(target)) return 'Toksoplazmaga antitanalar';
    if (/^цмв$/i.test(target)) return 'TsMV ga antitanalar';
    if (/^впг$/i.test(target)) return 'VPG ga antitanalar';
    if (/^краснухе$/i.test(target)) return 'Qizamiqqa antitanalar';
    return `${target} ga antitanalar`;
  }

  // Fallback: keep latin, transliterate cyrillic words via W
  if (!/[а-яё]/i.test(trimmed)) return trimmed;

  return trimmed
    .split(/(\s+|[-–—/(),.+])/g)
    .map((part) => {
      if (!/[а-яё]/i.test(part)) return part;
      const lower = part.toLowerCase().replace(/[ё]/g, 'е');
      if (W[lower]) {
        const uz = W[lower];
        return part[0] === part[0].toUpperCase() && uz[0] === uz[0].toLowerCase()
          ? uz.charAt(0).toUpperCase() + uz.slice(1)
          : uz;
      }
      return part;
    })
    .join('')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

const entries = [];
const missing = [];
for (const ru of ruList) {
  const uz = translateLab(ru);
  entries.push([ru, uz]);
  if (/[а-яА-ЯёЁ]/.test(uz) || /\b(revmatoidniy|tireotropniy|svobodniy|obshiy|bilan reaktiv)\b/i.test(uz)) {
    missing.push({ ru, uz });
  }
}

const lines = [
  '/**',
  ' * Laboratoriya tahlillari — barcha 466 ta aniq o\'zbek tarjimalari.',
  ' * scripts/generateLabExactUz.mjs orqali generatsiya qilingan.',
  ' */',
  'export const LAB_EXACT_PHRASES_UZ: [string, string][] = [',
];
for (const [ru, uz] of entries) {
  const ruEsc = ru.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const uzEsc = uz.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  lines.push(`  ['${ruEsc}', '${uzEsc}'],`);
}
lines.push('];', '');

const outTs = path.join(root, 'src/data/priceLabExactUz.ts');
fs.writeFileSync(outTs, lines.join('\n'), 'utf8');

console.log('Generated', entries.length, 'entries ->', outTs);
console.log('Potentially bad:', missing.length);
if (missing.length) {
  for (const x of missing.slice(0, 15)) console.log(' -', x.ru, '=>', x.uz);
}
