/**
 * Generate nginx map for site-level 301 redirects (Daavlin sections, clinic laser models, legacy paths).
 * Usage: npx tsx scripts/generateSiteNginxRedirects.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { buildSiteRedirectPairs } from '../src/seo/sitemapRedirectRules';

const OUT = path.join(process.cwd(), 'nginx', 'radeski-site-redirects.map.conf');

function buildNginxMap(pairs: Array<{ from: string; to: string }>): string {
  const lines = [
    '# Generated by scripts/generateSiteNginxRedirects.ts — do not edit manually.',
    'map $uri $radeski_site_redirect {',
    '    default "";',
  ];
  for (const { from, to } of pairs) {
    lines.push(`    ${from} ${to};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const pairs = buildSiteRedirectPairs();
mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, buildNginxMap(pairs), 'utf8');
console.log(`Wrote ${pairs.length} site redirects -> ${OUT}`);
